// PhoneBridge Local IPC — v1
// Package: phonebridge.localipc.v1
// Status: CONFIRMED (Phase 0) — contract ratified from Spike 01 (DEC-018).
// Source of truth for wire compatibility: this file + buf breaking checks.
//
// Scope and isolation rules (see docs/protocol.md):
// - This contract serves the SAME-USER, SAME-MACHINE boundary only:
//   Flutter UI <-> phonebridge daemon over a Unix domain socket.
// - It MUST NOT be exposed on any network listener and MUST NOT become part
//   of the device-to-device protocol (phonebridge.v1), which is a different
//   boundary with a different trust model. The daemon is the only component
//   that speaks both; StreamEventsResponse.envelope is opaque relay payload, not a
//   transport definition for phonebridge.v1.
// - phonebridge.spike.localipc.v1 (Spike 01) is a throwaway schema and was
//   never promoted; nothing here reuses it.
//
// Transport (ratified by Spike 01, DEC-018):
// - Socket: $XDG_RUNTIME_DIR/phonebridge/engine.sock
//   Directory created 0700, owned by the daemon's effective user; socket
//   file 0600. A stale socket from a crashed predecessor is removed at
//   startup only after verifying no live listener exists.
// - Gate 1 (primary, kernel-verified): SO_PEERCRED on every accepted
//   connection; peers whose UID differs from the daemon's effective UID are
//   rejected pre-auth (gRPC transport credentials).
// - Gate 2 (defense-in-depth): gRPC metadata
//   `authorization: Bearer <token>` on every call, constant-time compared.
//   Token provisioning: at startup the daemon generates >= 256 bits from a
//   CSPRNG and writes it to $XDG_RUNTIME_DIR/phonebridge/token, mode 0600,
//   owned by the daemon's effective user. A legitimate client is any
//   process running as the same OS user (exactly the privilege the uid gate
//   enforces): it reads that file and attaches the bearer metadata to every
//   call. The token rotates on every daemon start; on UNAUTHENTICATED the
//   client re-reads the file and reconnects. The bearer token covers
//   socket-permission misconfiguration and uncooperative same-uid
//   processes; on a correctly configured system the uid gate is the
//   primary boundary.
// - Lifecycle: the daemon is a foreground process (systemd user service
//   Type=simple, Restart=on-failure); SIGTERM -> graceful stop, streams end
//   cleanly, socket removed. Clients reconnect with backoff; continuity is
//   detected via HandshakeResponse.daemon_generation and StreamEventsResponse.seq.
// - Payloads: gRPC's default 4 MiB message ceiling applies. Bulk content
//   (file bytes, large clipboard bodies) MUST additionally be chunked at
//   <= 64 KiB per message (Spike 01: a 64 KiB message costs ~2x a small
//   one; chunking bounds relay latency and head-of-line blocking).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: phonebridge/localipc/v1/local_ipc.proto

package phonebridgelocalipcv1

import (
	phonebridgev1 "github.com/om051p/phonebridge/core/pkg/protocol/phonebridgev1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HandshakeRequest advertises the client's local-IPC protocol support.
type HandshakeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Highest phonebridge.localipc protocol version the client implements.
	// Currently always 1. The server negotiates down to its own maximum.
	ClientVersion uint32 `protobuf:"varint,1,opt,name=client_version,json=clientVersion,proto3" json:"client_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HandshakeRequest) Reset() {
	*x = HandshakeRequest{}
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeRequest) ProtoMessage() {}

func (x *HandshakeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeRequest.ProtoReflect.Descriptor instead.
func (*HandshakeRequest) Descriptor() ([]byte, []int) {
	return file_phonebridge_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *HandshakeRequest) GetClientVersion() uint32 {
	if x != nil {
		return x.ClientVersion
	}
	return 0
}

// HandshakeResponse answers Handshake.
type HandshakeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Version selected for this connection: min(client_version, server max).
	// Currently always 1.
	NegotiatedVersion uint32 `protobuf:"varint,1,opt,name=negotiated_version,json=negotiatedVersion,proto3" json:"negotiated_version,omitempty"`
	// Daemon build/version string (informational identity for logs/debug).
	ServerVersion string `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	// Identifier of the daemon process instance. Changes on every daemon
	// (re)start; clients use it to detect daemon replacement across
	// reconnects. Matches StreamEventsResponse.daemon_generation on later streams.
	DaemonGeneration uint64 `protobuf:"varint,3,opt,name=daemon_generation,json=daemonGeneration,proto3" json:"daemon_generation,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *HandshakeResponse) Reset() {
	*x = HandshakeResponse{}
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HandshakeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandshakeResponse) ProtoMessage() {}

func (x *HandshakeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandshakeResponse.ProtoReflect.Descriptor instead.
func (*HandshakeResponse) Descriptor() ([]byte, []int) {
	return file_phonebridge_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *HandshakeResponse) GetNegotiatedVersion() uint32 {
	if x != nil {
		return x.NegotiatedVersion
	}
	return 0
}

func (x *HandshakeResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HandshakeResponse) GetDaemonGeneration() uint64 {
	if x != nil {
		return x.DaemonGeneration
	}
	return 0
}

// PingRequest carries a caller nonce for reply correlation.
type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller-chosen nonce, echoed in PingResponse.
	Nonce         uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_phonebridge_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *PingRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

// PingResponse answers PingRequest.
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echo of PingRequest.nonce.
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Daemon build/version string (identity check after a reconnect).
	ServerVersion string `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_phonebridge_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *PingResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *PingResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

// StreamEventsRequest subscribes to relayed device-protocol events.
// Intentionally empty in v1: future filters (event kinds, device ids) are
// added as optional fields; older servers ignore unknown fields.
type StreamEventsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsRequest) Reset() {
	*x = StreamEventsRequest{}
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsRequest) ProtoMessage() {}

func (x *StreamEventsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsRequest.ProtoReflect.Descriptor instead.
func (*StreamEventsRequest) Descriptor() ([]byte, []int) {
	return file_phonebridge_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{4}
}

// StreamEventsResponse is one pushed message on the StreamEvents stream.
// (the "local event" of DEC-018; the type is named to satisfy the repo's STANDARD lint)
type StreamEventsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-stream monotonic sequence starting at 1. The local ordering
	// authority — clients detect gaps and must resubscribe/resync via Health.
	// (Distinct from Envelope.sequence, which orders the DEVICE session.)
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Daemon instance identifier; equals HandshakeResponse.daemon_generation for the
	// serving daemon. A change means the daemon restarted under the client.
	DaemonGeneration uint64 `protobuf:"varint,2,opt,name=daemon_generation,json=daemonGeneration,proto3" json:"daemon_generation,omitempty"`
	// Opaque relayed device-protocol message (phonebridge.v1). The daemon
	// forwards the Envelope verbatim; the UI decodes device payloads
	// directly. Pass-through framing per DEC-018: this is payload relay,
	// NOT a new transport for phonebridge.v1, and LocalEngine is never a
	// device peer.
	Envelope      *phonebridgev1.Envelope `protobuf:"bytes,3,opt,name=envelope,proto3" json:"envelope,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamEventsResponse) Reset() {
	*x = StreamEventsResponse{}
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamEventsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamEventsResponse) ProtoMessage() {}

func (x *StreamEventsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamEventsResponse.ProtoReflect.Descriptor instead.
func (*StreamEventsResponse) Descriptor() ([]byte, []int) {
	return file_phonebridge_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *StreamEventsResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *StreamEventsResponse) GetDaemonGeneration() uint64 {
	if x != nil {
		return x.DaemonGeneration
	}
	return 0
}

func (x *StreamEventsResponse) GetEnvelope() *phonebridgev1.Envelope {
	if x != nil {
		return x.Envelope
	}
	return nil
}

// HealthRequest is empty.
type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_phonebridge_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{6}
}

// HealthResponse answers Health.
type HealthResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True once the daemon is serving (its READY state).
	Ready bool `protobuf:"varint,1,opt,name=ready,proto3" json:"ready,omitempty"`
	// Daemon instance identifier (see HandshakeResponse.daemon_generation).
	DaemonGeneration uint64 `protobuf:"varint,2,opt,name=daemon_generation,json=daemonGeneration,proto3" json:"daemon_generation,omitempty"`
	// Daemon build/version string.
	ServerVersion string `protobuf:"bytes,3,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	// Milliseconds since daemon start (informational).
	UptimeMs      uint64 `protobuf:"varint,4,opt,name=uptime_ms,json=uptimeMs,proto3" json:"uptime_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_localipc_v1_local_ipc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_phonebridge_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *HealthResponse) GetDaemonGeneration() uint64 {
	if x != nil {
		return x.DaemonGeneration
	}
	return 0
}

func (x *HealthResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *HealthResponse) GetUptimeMs() uint64 {
	if x != nil {
		return x.UptimeMs
	}
	return 0
}

var File_phonebridge_localipc_v1_local_ipc_proto protoreflect.FileDescriptor

const file_phonebridge_localipc_v1_local_ipc_proto_rawDesc = "" +
	"\n" +
	"'phonebridge/localipc/v1/local_ipc.proto\x12\x17phonebridge.localipc.v1\x1a phonebridge/v1/phonebridge.proto\"9\n" +
	"\x10HandshakeRequest\x12%\n" +
	"\x0eclient_version\x18\x01 \x01(\rR\rclientVersion\"\x96\x01\n" +
	"\x11HandshakeResponse\x12-\n" +
	"\x12negotiated_version\x18\x01 \x01(\rR\x11negotiatedVersion\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12+\n" +
	"\x11daemon_generation\x18\x03 \x01(\x04R\x10daemonGeneration\"#\n" +
	"\vPingRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"K\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\"\x15\n" +
	"\x13StreamEventsRequest\"\x8b\x01\n" +
	"\x14StreamEventsResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12+\n" +
	"\x11daemon_generation\x18\x02 \x01(\x04R\x10daemonGeneration\x124\n" +
	"\benvelope\x18\x03 \x01(\v2\x18.phonebridge.v1.EnvelopeR\benvelope\"\x0f\n" +
	"\rHealthRequest\"\x97\x01\n" +
	"\x0eHealthResponse\x12\x14\n" +
	"\x05ready\x18\x01 \x01(\bR\x05ready\x12+\n" +
	"\x11daemon_generation\x18\x02 \x01(\x04R\x10daemonGeneration\x12%\n" +
	"\x0eserver_version\x18\x03 \x01(\tR\rserverVersion\x12\x1b\n" +
	"\tuptime_ms\x18\x04 \x01(\x04R\buptimeMs2\x97\x03\n" +
	"\x12LocalEngineService\x12b\n" +
	"\tHandshake\x12).phonebridge.localipc.v1.HandshakeRequest\x1a*.phonebridge.localipc.v1.HandshakeResponse\x12S\n" +
	"\x04Ping\x12$.phonebridge.localipc.v1.PingRequest\x1a%.phonebridge.localipc.v1.PingResponse\x12m\n" +
	"\fStreamEvents\x12,.phonebridge.localipc.v1.StreamEventsRequest\x1a-.phonebridge.localipc.v1.StreamEventsResponse0\x01\x12Y\n" +
	"\x06Health\x12&.phonebridge.localipc.v1.HealthRequest\x1a'.phonebridge.localipc.v1.HealthResponseB\x82\x01\n" +
	"!dev.phonebridge.proto.localipc.v1P\x01Z[github.com/om051p/phonebridge/core/pkg/protocol/phonebridgelocalipcv1;phonebridgelocalipcv1b\x06proto3"

var (
	file_phonebridge_localipc_v1_local_ipc_proto_rawDescOnce sync.Once
	file_phonebridge_localipc_v1_local_ipc_proto_rawDescData []byte
)

func file_phonebridge_localipc_v1_local_ipc_proto_rawDescGZIP() []byte {
	file_phonebridge_localipc_v1_local_ipc_proto_rawDescOnce.Do(func() {
		file_phonebridge_localipc_v1_local_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_phonebridge_localipc_v1_local_ipc_proto_rawDesc), len(file_phonebridge_localipc_v1_local_ipc_proto_rawDesc)))
	})
	return file_phonebridge_localipc_v1_local_ipc_proto_rawDescData
}

var file_phonebridge_localipc_v1_local_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_phonebridge_localipc_v1_local_ipc_proto_goTypes = []any{
	(*HandshakeRequest)(nil),       // 0: phonebridge.localipc.v1.HandshakeRequest
	(*HandshakeResponse)(nil),      // 1: phonebridge.localipc.v1.HandshakeResponse
	(*PingRequest)(nil),            // 2: phonebridge.localipc.v1.PingRequest
	(*PingResponse)(nil),           // 3: phonebridge.localipc.v1.PingResponse
	(*StreamEventsRequest)(nil),    // 4: phonebridge.localipc.v1.StreamEventsRequest
	(*StreamEventsResponse)(nil),   // 5: phonebridge.localipc.v1.StreamEventsResponse
	(*HealthRequest)(nil),          // 6: phonebridge.localipc.v1.HealthRequest
	(*HealthResponse)(nil),         // 7: phonebridge.localipc.v1.HealthResponse
	(*phonebridgev1.Envelope)(nil), // 8: phonebridge.v1.Envelope
}
var file_phonebridge_localipc_v1_local_ipc_proto_depIdxs = []int32{
	8, // 0: phonebridge.localipc.v1.StreamEventsResponse.envelope:type_name -> phonebridge.v1.Envelope
	0, // 1: phonebridge.localipc.v1.LocalEngineService.Handshake:input_type -> phonebridge.localipc.v1.HandshakeRequest
	2, // 2: phonebridge.localipc.v1.LocalEngineService.Ping:input_type -> phonebridge.localipc.v1.PingRequest
	4, // 3: phonebridge.localipc.v1.LocalEngineService.StreamEvents:input_type -> phonebridge.localipc.v1.StreamEventsRequest
	6, // 4: phonebridge.localipc.v1.LocalEngineService.Health:input_type -> phonebridge.localipc.v1.HealthRequest
	1, // 5: phonebridge.localipc.v1.LocalEngineService.Handshake:output_type -> phonebridge.localipc.v1.HandshakeResponse
	3, // 6: phonebridge.localipc.v1.LocalEngineService.Ping:output_type -> phonebridge.localipc.v1.PingResponse
	5, // 7: phonebridge.localipc.v1.LocalEngineService.StreamEvents:output_type -> phonebridge.localipc.v1.StreamEventsResponse
	7, // 8: phonebridge.localipc.v1.LocalEngineService.Health:output_type -> phonebridge.localipc.v1.HealthResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_phonebridge_localipc_v1_local_ipc_proto_init() }
func file_phonebridge_localipc_v1_local_ipc_proto_init() {
	if File_phonebridge_localipc_v1_local_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_phonebridge_localipc_v1_local_ipc_proto_rawDesc), len(file_phonebridge_localipc_v1_local_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_phonebridge_localipc_v1_local_ipc_proto_goTypes,
		DependencyIndexes: file_phonebridge_localipc_v1_local_ipc_proto_depIdxs,
		MessageInfos:      file_phonebridge_localipc_v1_local_ipc_proto_msgTypes,
	}.Build()
	File_phonebridge_localipc_v1_local_ipc_proto = out.File
	file_phonebridge_localipc_v1_local_ipc_proto_goTypes = nil
	file_phonebridge_localipc_v1_local_ipc_proto_depIdxs = nil
}
