// PhoneBridge Local IPC — v1
// Package: phonebridge.localipc.v1
// Status: CONFIRMED (Phase 0) — contract ratified from Spike 01 (DEC-018).
// Source of truth for wire compatibility: this file + buf breaking checks.
//
// Scope and isolation rules (see docs/protocol.md):
// - This contract serves the SAME-USER, SAME-MACHINE boundary only:
//   Flutter UI <-> phonebridge daemon over a Unix domain socket.
// - It MUST NOT be exposed on any network listener and MUST NOT become part
//   of the device-to-device protocol (phonebridge.v1), which is a different
//   boundary with a different trust model. The daemon is the only component
//   that speaks both; StreamEventsResponse.envelope is opaque relay payload, not a
//   transport definition for phonebridge.v1.
// - phonebridge.spike.localipc.v1 (Spike 01) is a throwaway schema and was
//   never promoted; nothing here reuses it.
//
// Transport (ratified by Spike 01, DEC-018):
// - Socket: $XDG_RUNTIME_DIR/phonebridge/engine.sock
//   Directory created 0700, owned by the daemon's effective user; socket
//   file 0600. A stale socket from a crashed predecessor is removed at
//   startup only after verifying no live listener exists.
// - Gate 1 (primary, kernel-verified): SO_PEERCRED on every accepted
//   connection; peers whose UID differs from the daemon's effective UID are
//   rejected pre-auth (gRPC transport credentials).
// - Gate 2 (defense-in-depth): gRPC metadata
//   `authorization: Bearer <token>` on every call, constant-time compared.
//   Token provisioning: at startup the daemon generates >= 256 bits from a
//   CSPRNG and writes it to $XDG_RUNTIME_DIR/phonebridge/token, mode 0600,
//   owned by the daemon's effective user. A legitimate client is any
//   process running as the same OS user (exactly the privilege the uid gate
//   enforces): it reads that file and attaches the bearer metadata to every
//   call. The token rotates on every daemon start; on UNAUTHENTICATED the
//   client re-reads the file and reconnects. The bearer token covers
//   socket-permission misconfiguration and uncooperative same-uid
//   processes; on a correctly configured system the uid gate is the
//   primary boundary.
// - Lifecycle: the daemon is a foreground process (systemd user service
//   Type=simple, Restart=on-failure); SIGTERM -> graceful stop, streams end
//   cleanly, socket removed. Clients reconnect with backoff; continuity is
//   detected via HandshakeResponse.daemon_generation and StreamEventsResponse.seq.
// - Payloads: gRPC's default 4 MiB message ceiling applies. Bulk content
//   (file bytes, large clipboard bodies) MUST additionally be chunked at
//   <= 64 KiB per message (Spike 01: a 64 KiB message costs ~2x a small
//   one; chunking bounds relay latency and head-of-line blocking).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: phonebridge/localipc/v1/local_ipc.proto

package phonebridgelocalipcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalEngineService_Handshake_FullMethodName    = "/phonebridge.localipc.v1.LocalEngineService/Handshake"
	LocalEngineService_Ping_FullMethodName         = "/phonebridge.localipc.v1.LocalEngineService/Ping"
	LocalEngineService_StreamEvents_FullMethodName = "/phonebridge.localipc.v1.LocalEngineService/StreamEvents"
	LocalEngineService_Health_FullMethodName       = "/phonebridge.localipc.v1.LocalEngineService/Health"
)

// LocalEngineServiceClient is the client API for LocalEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------------------------
// LocalEngineService — the UI-facing engine service on the local Unix socket.
// ---------------------------------------------------------------------------
type LocalEngineServiceClient interface {
	// Handshake negotiates the local protocol version and returns daemon
	// identity. Must be the first call on a new connection.
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Ping is a cheap liveness/reconnect probe.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// StreamEvents pushes relayed device-protocol messages to the UI.
	// Server-streaming; the daemon ends the stream cleanly on shutdown, and
	// the client re-subscribes with backoff after any stream end.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error)
	// Health reports daemon readiness without opening an event stream.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type localEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalEngineServiceClient(cc grpc.ClientConnInterface) LocalEngineServiceClient {
	return &localEngineServiceClient{cc}
}

func (c *localEngineServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalEngineService_ServiceDesc.Streams[0], LocalEngineService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, StreamEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalEngineService_StreamEventsClient = grpc.ServerStreamingClient[StreamEventsResponse]

func (c *localEngineServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalEngineServiceServer is the server API for LocalEngineService service.
// All implementations should embed UnimplementedLocalEngineServiceServer
// for forward compatibility.
//
// ---------------------------------------------------------------------------
// LocalEngineService — the UI-facing engine service on the local Unix socket.
// ---------------------------------------------------------------------------
type LocalEngineServiceServer interface {
	// Handshake negotiates the local protocol version and returns daemon
	// identity. Must be the first call on a new connection.
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Ping is a cheap liveness/reconnect probe.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// StreamEvents pushes relayed device-protocol messages to the UI.
	// Server-streaming; the daemon ends the stream cleanly on shutdown, and
	// the client re-subscribes with backoff after any stream end.
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error
	// Health reports daemon readiness without opening an event stream.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
}

// UnimplementedLocalEngineServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalEngineServiceServer struct{}

func (UnimplementedLocalEngineServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedLocalEngineServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLocalEngineServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedLocalEngineServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLocalEngineServiceServer) testEmbeddedByValue() {}

// UnsafeLocalEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalEngineServiceServer will
// result in compilation errors.
type UnsafeLocalEngineServiceServer interface {
	mustEmbedUnimplementedLocalEngineServiceServer()
}

func RegisterLocalEngineServiceServer(s grpc.ServiceRegistrar, srv LocalEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedLocalEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalEngineService_ServiceDesc, srv)
}

func _LocalEngineService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalEngineServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, StreamEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalEngineService_StreamEventsServer = grpc.ServerStreamingServer[StreamEventsResponse]

func _LocalEngineService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalEngineService_ServiceDesc is the grpc.ServiceDesc for LocalEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "phonebridge.localipc.v1.LocalEngineService",
	HandlerType: (*LocalEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _LocalEngineService_Handshake_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _LocalEngineService_Ping_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LocalEngineService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _LocalEngineService_StreamEvents_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "phonebridge/localipc/v1/local_ipc.proto",
}
