// PhoneBridge Local IPC — v1
// Package: phonebridge.localipc.v1
// Status: CONFIRMED (Phase 0) — contract ratified from Spike 01 (DEC-018).
//         Session lifecycle extended in Phase 2 (DEC-022): requested/actual
//         media parameters and typed session reason codes.
//         Clipboard status/pull added in Phase 3 (DEC-023); file-transfer
//         RPCs and events added in Phase 4 (DEC-024).
// Source of truth for wire compatibility: this file + buf breaking checks.
//
// Scope and isolation rules (see docs/protocol.md):
// - This contract serves the SAME-USER, SAME-MACHINE boundary only:
//   Flutter UI <-> phonebridge daemon over a Unix domain socket.
// - It MUST NOT be exposed on any network listener and MUST NOT become part
//   of the device-to-device protocol (phonebridge.v1), which is a different
//   boundary with a different trust model. The daemon is the only component
//   that speaks both; StreamEventsResponse.envelope is opaque relay payload, not a
//   transport definition for phonebridge.v1.
// - phonebridge.spike.localipc.v1 (Spike 01) is a throwaway schema and was
//   never promoted; nothing here reuses it.
//
// Transport (ratified by Spike 01, DEC-018):
// - Socket: $XDG_RUNTIME_DIR/phonebridge/engine.sock
//   Directory created 0700, owned by the daemon's effective user; socket
//   file 0600. A stale socket from a crashed predecessor is removed at
//   startup only after verifying no live listener exists.
// - Gate 1 (primary, kernel-verified): SO_PEERCRED on every accepted
//   connection; peers whose UID differs from the daemon's effective UID are
//   rejected pre-auth (gRPC transport credentials).
// - Gate 2 (defense-in-depth): gRPC metadata
//   `authorization: Bearer <token>` on every call, constant-time compared.
//   Token provisioning and client acquisition mechanism:
//   1. Generation: At daemon startup, the daemon generates >= 256 bits of
//      cryptographically secure randomness from a CSPRNG (e.g. crypto/rand)
//      and writes it as a hex/ASCII string to $XDG_RUNTIME_DIR/phonebridge/token
//      (mode 0600, owned by the daemon's effective UID).
//   2. Client Discovery & Acquisition: The legitimate Flutter UI client,
//      executing as the same OS user, resolves the token file path
//      ($XDG_RUNTIME_DIR/phonebridge/token). If the file is not yet present at
//      client launch, the client polls with exponential backoff (e.g. 50ms,
//      100ms, up to 3s) until the daemon signals READY. The client reads the
//      token from the file into memory.
//   3. RPC Authentication: The client attaches the token to every gRPC call
//      via metadata: `authorization: Bearer <token>` (e.g., via grpc-dart
//      CallOptions(metadata: {'authorization': 'Bearer $token'})).
//   4. Rotation & Re-auth: The token rotates on every daemon start. When the
//      client receives gRPC status UNAUTHENTICATED (code 16), it invalidates
//      its in-memory token cache, re-reads the token file from disk, and
//      re-establishes the connection with backoff.
//   The bearer token covers socket-permission misconfiguration (e.g.
//   accidentally world-accessible socket files) and cross-namespace or
//   container leaks; on a correctly configured system under POSIX DAC the
//   uid gate is the primary boundary.
// - Lifecycle: the daemon is a foreground process (systemd user service
//   Type=simple, Restart=on-failure); SIGTERM -> graceful stop, streams end
//   cleanly, socket removed. Clients reconnect with backoff; continuity is
//   detected via HandshakeResponse.daemon_generation and StreamEventsResponse.seq.
// - Payloads: gRPC's default 4 MiB message ceiling applies. Bulk content
//   (file bytes, large clipboard bodies) MUST additionally be chunked at
//   <= 64 KiB per message (Spike 01: a 64 KiB message costs ~2x a small
//   one; chunking bounds relay latency and head-of-line blocking).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: phonebridge/localipc/v1/local_ipc.proto

package phonebridgelocalipcv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalEngineService_Handshake_FullMethodName            = "/phonebridge.localipc.v1.LocalEngineService/Handshake"
	LocalEngineService_Ping_FullMethodName                 = "/phonebridge.localipc.v1.LocalEngineService/Ping"
	LocalEngineService_StreamEvents_FullMethodName         = "/phonebridge.localipc.v1.LocalEngineService/StreamEvents"
	LocalEngineService_Health_FullMethodName               = "/phonebridge.localipc.v1.LocalEngineService/Health"
	LocalEngineService_StartSession_FullMethodName         = "/phonebridge.localipc.v1.LocalEngineService/StartSession"
	LocalEngineService_StopSession_FullMethodName          = "/phonebridge.localipc.v1.LocalEngineService/StopSession"
	LocalEngineService_GetSessionState_FullMethodName      = "/phonebridge.localipc.v1.LocalEngineService/GetSessionState"
	LocalEngineService_ListDevices_FullMethodName          = "/phonebridge.localipc.v1.LocalEngineService/ListDevices"
	LocalEngineService_PairDevice_FullMethodName           = "/phonebridge.localipc.v1.LocalEngineService/PairDevice"
	LocalEngineService_ConfirmPairing_FullMethodName       = "/phonebridge.localipc.v1.LocalEngineService/ConfirmPairing"
	LocalEngineService_ListTrustedDevices_FullMethodName   = "/phonebridge.localipc.v1.LocalEngineService/ListTrustedDevices"
	LocalEngineService_RevokeDevice_FullMethodName         = "/phonebridge.localipc.v1.LocalEngineService/RevokeDevice"
	LocalEngineService_GetClipboardStatus_FullMethodName   = "/phonebridge.localipc.v1.LocalEngineService/GetClipboardStatus"
	LocalEngineService_TriggerClipboardPull_FullMethodName = "/phonebridge.localipc.v1.LocalEngineService/TriggerClipboardPull"
	LocalEngineService_SendFile_FullMethodName             = "/phonebridge.localipc.v1.LocalEngineService/SendFile"
	LocalEngineService_CancelTransfer_FullMethodName       = "/phonebridge.localipc.v1.LocalEngineService/CancelTransfer"
	LocalEngineService_ListTransfers_FullMethodName        = "/phonebridge.localipc.v1.LocalEngineService/ListTransfers"
	LocalEngineService_StreamFrames_FullMethodName         = "/phonebridge.localipc.v1.LocalEngineService/StreamFrames"
)

// LocalEngineServiceClient is the client API for LocalEngineService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ---------------------------------------------------------------------------
// LocalEngineService — the UI-facing engine service on the local Unix socket.
// ---------------------------------------------------------------------------
type LocalEngineServiceClient interface {
	// Handshake negotiates the local protocol version and returns daemon
	// identity. Must be the first call on a new connection.
	Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error)
	// Ping is a cheap liveness/reconnect probe.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// StreamEvents pushes relayed device-protocol messages to the UI.
	// Server-streaming; the daemon ends the stream cleanly on shutdown, and
	// the client re-subscribes with backoff after any stream end.
	StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error)
	// Health reports daemon readiness without opening an event stream.
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
	// StartSession initiates a new connection session with a discovered phone.
	StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error)
	// StopSession cleanly terminates an active session.
	StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error)
	// GetSessionState queries the current phase, device, and metrics of a session.
	GetSessionState(ctx context.Context, in *GetSessionStateRequest, opts ...grpc.CallOption) (*GetSessionStateResponse, error)
	// ListDevices returns all currently discovered LAN devices from mDNS.
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	// PairDevice initiates pairing with a discovered LAN device.
	PairDevice(ctx context.Context, in *PairDeviceRequest, opts ...grpc.CallOption) (*PairDeviceResponse, error)
	// ConfirmPairing completes pairing by confirming the SAS.
	ConfirmPairing(ctx context.Context, in *ConfirmPairingRequest, opts ...grpc.CallOption) (*ConfirmPairingResponse, error)
	// ListTrustedDevices returns all trusted/paired devices.
	ListTrustedDevices(ctx context.Context, in *ListTrustedDevicesRequest, opts ...grpc.CallOption) (*ListTrustedDevicesResponse, error)
	// RevokeDevice revokes trust for a previously paired device.
	RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error)
	// GetClipboardStatus returns the current status of the host clipboard adapter and engine.
	GetClipboardStatus(ctx context.Context, in *GetClipboardStatusRequest, opts ...grpc.CallOption) (*GetClipboardStatusResponse, error)
	// TriggerClipboardPull reads the host clipboard and synchronizes it to the active peer.
	TriggerClipboardPull(ctx context.Context, in *TriggerClipboardPullRequest, opts ...grpc.CallOption) (*TriggerClipboardPullResponse, error)
	// SendFile offers a local file to the active peer over the session's
	// dedicated "transfer" DataChannel (DEC-024). The daemon reads local_path
	// itself: file bytes never cross this local boundary, and no whole file is
	// buffered anywhere (streaming chunked I/O).
	SendFile(ctx context.Context, in *SendFileRequest, opts ...grpc.CallOption) (*SendFileResponse, error)
	// CancelTransfer aborts an in-flight transfer in either direction. The
	// cancel frame goes to the peer and the partial file is deleted locally.
	CancelTransfer(ctx context.Context, in *CancelTransferRequest, opts ...grpc.CallOption) (*CancelTransferResponse, error)
	// ListTransfers returns in-flight transfers plus the recent in-memory
	// history (Phase 4 does not persist history across daemon restarts).
	ListTransfers(ctx context.Context, in *ListTransfersRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error)
	// StreamFrames pushes encoded video frames of the active session to the UI
	// renderer (Phase 6 Slice 3, additive). Deliberately a SEPARATE stream from
	// StreamEvents: control events must never be starved or dropped by frame
	// traffic, and frames are opt-in per subscriber (one renderer at a time,
	// DEC-018's one-consumer rule). v1 carries JPEG frames produced by the
	// daemon-side tap; the message shape is transport-generic (chunked opaque
	// image bytes + geometry). The server ends the stream when the session it
	// is bound to reaches a terminal state; clients resubscribe via their
	// existing backoff pattern only while a session is live.
	StreamFrames(ctx context.Context, in *StreamFramesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamFramesResponse], error)
}

type localEngineServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalEngineServiceClient(cc grpc.ClientConnInterface) LocalEngineServiceClient {
	return &localEngineServiceClient{cc}
}

func (c *localEngineServiceClient) Handshake(ctx context.Context, in *HandshakeRequest, opts ...grpc.CallOption) (*HandshakeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HandshakeResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_Handshake_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) StreamEvents(ctx context.Context, in *StreamEventsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamEventsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalEngineService_ServiceDesc.Streams[0], LocalEngineService_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamEventsRequest, StreamEventsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalEngineService_StreamEventsClient = grpc.ServerStreamingClient[StreamEventsResponse]

func (c *localEngineServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) StartSession(ctx context.Context, in *StartSessionRequest, opts ...grpc.CallOption) (*StartSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StartSessionResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_StartSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) StopSession(ctx context.Context, in *StopSessionRequest, opts ...grpc.CallOption) (*StopSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopSessionResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_StopSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) GetSessionState(ctx context.Context, in *GetSessionStateRequest, opts ...grpc.CallOption) (*GetSessionStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionStateResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_GetSessionState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_ListDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) PairDevice(ctx context.Context, in *PairDeviceRequest, opts ...grpc.CallOption) (*PairDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairDeviceResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_PairDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) ConfirmPairing(ctx context.Context, in *ConfirmPairingRequest, opts ...grpc.CallOption) (*ConfirmPairingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ConfirmPairingResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_ConfirmPairing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) ListTrustedDevices(ctx context.Context, in *ListTrustedDevicesRequest, opts ...grpc.CallOption) (*ListTrustedDevicesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTrustedDevicesResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_ListTrustedDevices_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) RevokeDevice(ctx context.Context, in *RevokeDeviceRequest, opts ...grpc.CallOption) (*RevokeDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeDeviceResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_RevokeDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) GetClipboardStatus(ctx context.Context, in *GetClipboardStatusRequest, opts ...grpc.CallOption) (*GetClipboardStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClipboardStatusResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_GetClipboardStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) TriggerClipboardPull(ctx context.Context, in *TriggerClipboardPullRequest, opts ...grpc.CallOption) (*TriggerClipboardPullResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TriggerClipboardPullResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_TriggerClipboardPull_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) SendFile(ctx context.Context, in *SendFileRequest, opts ...grpc.CallOption) (*SendFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendFileResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_SendFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) CancelTransfer(ctx context.Context, in *CancelTransferRequest, opts ...grpc.CallOption) (*CancelTransferResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelTransferResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_CancelTransfer_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) ListTransfers(ctx context.Context, in *ListTransfersRequest, opts ...grpc.CallOption) (*ListTransfersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTransfersResponse)
	err := c.cc.Invoke(ctx, LocalEngineService_ListTransfers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localEngineServiceClient) StreamFrames(ctx context.Context, in *StreamFramesRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamFramesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalEngineService_ServiceDesc.Streams[1], LocalEngineService_StreamFrames_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamFramesRequest, StreamFramesResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalEngineService_StreamFramesClient = grpc.ServerStreamingClient[StreamFramesResponse]

// LocalEngineServiceServer is the server API for LocalEngineService service.
// All implementations should embed UnimplementedLocalEngineServiceServer
// for forward compatibility.
//
// ---------------------------------------------------------------------------
// LocalEngineService — the UI-facing engine service on the local Unix socket.
// ---------------------------------------------------------------------------
type LocalEngineServiceServer interface {
	// Handshake negotiates the local protocol version and returns daemon
	// identity. Must be the first call on a new connection.
	Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error)
	// Ping is a cheap liveness/reconnect probe.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// StreamEvents pushes relayed device-protocol messages to the UI.
	// Server-streaming; the daemon ends the stream cleanly on shutdown, and
	// the client re-subscribes with backoff after any stream end.
	StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error
	// Health reports daemon readiness without opening an event stream.
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	// StartSession initiates a new connection session with a discovered phone.
	StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error)
	// StopSession cleanly terminates an active session.
	StopSession(context.Context, *StopSessionRequest) (*StopSessionResponse, error)
	// GetSessionState queries the current phase, device, and metrics of a session.
	GetSessionState(context.Context, *GetSessionStateRequest) (*GetSessionStateResponse, error)
	// ListDevices returns all currently discovered LAN devices from mDNS.
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	// PairDevice initiates pairing with a discovered LAN device.
	PairDevice(context.Context, *PairDeviceRequest) (*PairDeviceResponse, error)
	// ConfirmPairing completes pairing by confirming the SAS.
	ConfirmPairing(context.Context, *ConfirmPairingRequest) (*ConfirmPairingResponse, error)
	// ListTrustedDevices returns all trusted/paired devices.
	ListTrustedDevices(context.Context, *ListTrustedDevicesRequest) (*ListTrustedDevicesResponse, error)
	// RevokeDevice revokes trust for a previously paired device.
	RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error)
	// GetClipboardStatus returns the current status of the host clipboard adapter and engine.
	GetClipboardStatus(context.Context, *GetClipboardStatusRequest) (*GetClipboardStatusResponse, error)
	// TriggerClipboardPull reads the host clipboard and synchronizes it to the active peer.
	TriggerClipboardPull(context.Context, *TriggerClipboardPullRequest) (*TriggerClipboardPullResponse, error)
	// SendFile offers a local file to the active peer over the session's
	// dedicated "transfer" DataChannel (DEC-024). The daemon reads local_path
	// itself: file bytes never cross this local boundary, and no whole file is
	// buffered anywhere (streaming chunked I/O).
	SendFile(context.Context, *SendFileRequest) (*SendFileResponse, error)
	// CancelTransfer aborts an in-flight transfer in either direction. The
	// cancel frame goes to the peer and the partial file is deleted locally.
	CancelTransfer(context.Context, *CancelTransferRequest) (*CancelTransferResponse, error)
	// ListTransfers returns in-flight transfers plus the recent in-memory
	// history (Phase 4 does not persist history across daemon restarts).
	ListTransfers(context.Context, *ListTransfersRequest) (*ListTransfersResponse, error)
	// StreamFrames pushes encoded video frames of the active session to the UI
	// renderer (Phase 6 Slice 3, additive). Deliberately a SEPARATE stream from
	// StreamEvents: control events must never be starved or dropped by frame
	// traffic, and frames are opt-in per subscriber (one renderer at a time,
	// DEC-018's one-consumer rule). v1 carries JPEG frames produced by the
	// daemon-side tap; the message shape is transport-generic (chunked opaque
	// image bytes + geometry). The server ends the stream when the session it
	// is bound to reaches a terminal state; clients resubscribe via their
	// existing backoff pattern only while a session is live.
	StreamFrames(*StreamFramesRequest, grpc.ServerStreamingServer[StreamFramesResponse]) error
}

// UnimplementedLocalEngineServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalEngineServiceServer struct{}

func (UnimplementedLocalEngineServiceServer) Handshake(context.Context, *HandshakeRequest) (*HandshakeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handshake not implemented")
}
func (UnimplementedLocalEngineServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLocalEngineServiceServer) StreamEvents(*StreamEventsRequest, grpc.ServerStreamingServer[StreamEventsResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedLocalEngineServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedLocalEngineServiceServer) StartSession(context.Context, *StartSessionRequest) (*StartSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartSession not implemented")
}
func (UnimplementedLocalEngineServiceServer) StopSession(context.Context, *StopSessionRequest) (*StopSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopSession not implemented")
}
func (UnimplementedLocalEngineServiceServer) GetSessionState(context.Context, *GetSessionStateRequest) (*GetSessionStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSessionState not implemented")
}
func (UnimplementedLocalEngineServiceServer) ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (UnimplementedLocalEngineServiceServer) PairDevice(context.Context, *PairDeviceRequest) (*PairDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PairDevice not implemented")
}
func (UnimplementedLocalEngineServiceServer) ConfirmPairing(context.Context, *ConfirmPairingRequest) (*ConfirmPairingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ConfirmPairing not implemented")
}
func (UnimplementedLocalEngineServiceServer) ListTrustedDevices(context.Context, *ListTrustedDevicesRequest) (*ListTrustedDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTrustedDevices not implemented")
}
func (UnimplementedLocalEngineServiceServer) RevokeDevice(context.Context, *RevokeDeviceRequest) (*RevokeDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RevokeDevice not implemented")
}
func (UnimplementedLocalEngineServiceServer) GetClipboardStatus(context.Context, *GetClipboardStatusRequest) (*GetClipboardStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClipboardStatus not implemented")
}
func (UnimplementedLocalEngineServiceServer) TriggerClipboardPull(context.Context, *TriggerClipboardPullRequest) (*TriggerClipboardPullResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TriggerClipboardPull not implemented")
}
func (UnimplementedLocalEngineServiceServer) SendFile(context.Context, *SendFileRequest) (*SendFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendFile not implemented")
}
func (UnimplementedLocalEngineServiceServer) CancelTransfer(context.Context, *CancelTransferRequest) (*CancelTransferResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CancelTransfer not implemented")
}
func (UnimplementedLocalEngineServiceServer) ListTransfers(context.Context, *ListTransfersRequest) (*ListTransfersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTransfers not implemented")
}
func (UnimplementedLocalEngineServiceServer) StreamFrames(*StreamFramesRequest, grpc.ServerStreamingServer[StreamFramesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method StreamFrames not implemented")
}
func (UnimplementedLocalEngineServiceServer) testEmbeddedByValue() {}

// UnsafeLocalEngineServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalEngineServiceServer will
// result in compilation errors.
type UnsafeLocalEngineServiceServer interface {
	mustEmbedUnimplementedLocalEngineServiceServer()
}

func RegisterLocalEngineServiceServer(s grpc.ServiceRegistrar, srv LocalEngineServiceServer) {
	// If the following call pancis, it indicates UnimplementedLocalEngineServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalEngineService_ServiceDesc, srv)
}

func _LocalEngineService_Handshake_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandshakeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).Handshake(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_Handshake_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).Handshake(ctx, req.(*HandshakeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamEventsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalEngineServiceServer).StreamEvents(m, &grpc.GenericServerStream[StreamEventsRequest, StreamEventsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalEngineService_StreamEventsServer = grpc.ServerStreamingServer[StreamEventsResponse]

func _LocalEngineService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_StartSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).StartSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_StartSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).StartSession(ctx, req.(*StartSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_StopSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).StopSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_StopSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).StopSession(ctx, req.(*StopSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_GetSessionState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).GetSessionState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_GetSessionState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).GetSessionState(ctx, req.(*GetSessionStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_ListDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_PairDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PairDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).PairDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_PairDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).PairDevice(ctx, req.(*PairDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_ConfirmPairing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPairingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).ConfirmPairing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_ConfirmPairing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).ConfirmPairing(ctx, req.(*ConfirmPairingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_ListTrustedDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTrustedDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).ListTrustedDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_ListTrustedDevices_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).ListTrustedDevices(ctx, req.(*ListTrustedDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_RevokeDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).RevokeDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_RevokeDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).RevokeDevice(ctx, req.(*RevokeDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_GetClipboardStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClipboardStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).GetClipboardStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_GetClipboardStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).GetClipboardStatus(ctx, req.(*GetClipboardStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_TriggerClipboardPull_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TriggerClipboardPullRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).TriggerClipboardPull(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_TriggerClipboardPull_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).TriggerClipboardPull(ctx, req.(*TriggerClipboardPullRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_SendFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).SendFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_SendFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).SendFile(ctx, req.(*SendFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_CancelTransfer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelTransferRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).CancelTransfer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_CancelTransfer_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).CancelTransfer(ctx, req.(*CancelTransferRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_ListTransfers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTransfersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalEngineServiceServer).ListTransfers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalEngineService_ListTransfers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalEngineServiceServer).ListTransfers(ctx, req.(*ListTransfersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalEngineService_StreamFrames_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamFramesRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalEngineServiceServer).StreamFrames(m, &grpc.GenericServerStream[StreamFramesRequest, StreamFramesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalEngineService_StreamFramesServer = grpc.ServerStreamingServer[StreamFramesResponse]

// LocalEngineService_ServiceDesc is the grpc.ServiceDesc for LocalEngineService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalEngineService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "phonebridge.localipc.v1.LocalEngineService",
	HandlerType: (*LocalEngineServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handshake",
			Handler:    _LocalEngineService_Handshake_Handler,
		},
		{
			MethodName: "Ping",
			Handler:    _LocalEngineService_Ping_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _LocalEngineService_Health_Handler,
		},
		{
			MethodName: "StartSession",
			Handler:    _LocalEngineService_StartSession_Handler,
		},
		{
			MethodName: "StopSession",
			Handler:    _LocalEngineService_StopSession_Handler,
		},
		{
			MethodName: "GetSessionState",
			Handler:    _LocalEngineService_GetSessionState_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _LocalEngineService_ListDevices_Handler,
		},
		{
			MethodName: "PairDevice",
			Handler:    _LocalEngineService_PairDevice_Handler,
		},
		{
			MethodName: "ConfirmPairing",
			Handler:    _LocalEngineService_ConfirmPairing_Handler,
		},
		{
			MethodName: "ListTrustedDevices",
			Handler:    _LocalEngineService_ListTrustedDevices_Handler,
		},
		{
			MethodName: "RevokeDevice",
			Handler:    _LocalEngineService_RevokeDevice_Handler,
		},
		{
			MethodName: "GetClipboardStatus",
			Handler:    _LocalEngineService_GetClipboardStatus_Handler,
		},
		{
			MethodName: "TriggerClipboardPull",
			Handler:    _LocalEngineService_TriggerClipboardPull_Handler,
		},
		{
			MethodName: "SendFile",
			Handler:    _LocalEngineService_SendFile_Handler,
		},
		{
			MethodName: "CancelTransfer",
			Handler:    _LocalEngineService_CancelTransfer_Handler,
		},
		{
			MethodName: "ListTransfers",
			Handler:    _LocalEngineService_ListTransfers_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _LocalEngineService_StreamEvents_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StreamFrames",
			Handler:       _LocalEngineService_StreamFrames_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "phonebridge/localipc/v1/local_ipc.proto",
}
