// PhoneBridge Spike 01 — provisional local IPC contract (EXPERIMENTAL).
//
// This file exists ONLY to exercise the Flutter <-> Go local transport
// boundary on Linux. It is deliberately NOT `phonebridge.v1`:
//   * `phonebridge.v1` (proto/phonebridge/v1/phonebridge.proto) is the
//     device <-> device wire protocol. It has no `service`, because the
//     local IPC contract is a different boundary with a different trust
//     model (same machine, same user) and is decided by this spike.
//   * Keeping the spike contract separate means the spike cannot freeze or
//     drift the product schema (see docs/decisions.md DEC-014/DEC-015).
//
// The contract is intentionally minimal (Ping/Pong + push + peer identity).
// No product feature is modelled here.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: phonebridge/spike/localipc/v1/local_ipc.proto

package spikepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// PingRequest carries a caller nonce and an optional payload used to sweep
// message sizes (chunking evidence for future file/clipboard transfer).
type PingRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller-chosen nonce, echoed back to prove the reply belongs to the call.
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Opaque payload; length drives the size sweep (0..64 KiB in the spike).
	Payload       []byte `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *PingRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// PingResponse is the daemon's reply to PingRequest.
type PingResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Echo of PingRequest.nonce.
	Nonce uint64 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Daemon build/version string (identity + reconnect check).
	ServerVersion string `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	// Echo of PingRequest.payload (possibly truncated by the daemon).
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// Daemon wall clock (CLOCK_REALTIME, nanoseconds) when the request was
	// received; lets the client split transit from service time.
	ServerRecvUnixNanos uint64 `protobuf:"varint,4,opt,name=server_recv_unix_nanos,json=serverRecvUnixNanos,proto3" json:"server_recv_unix_nanos,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *PingResponse) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *PingResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *PingResponse) GetServerRecvUnixNanos() uint64 {
	if x != nil {
		return x.ServerRecvUnixNanos
	}
	return 0
}

// SubscribeRequest configures the push test.
type SubscribeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of events to emit before the stream ends.
	Count uint32 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	// Delay between events, in milliseconds.
	IntervalMs uint32 `protobuf:"varint,2,opt,name=interval_ms,json=intervalMs,proto3" json:"interval_ms,omitempty"`
	// Bytes of synthetic payload attached to each event.
	PayloadSize   uint32 `protobuf:"varint,3,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{2}
}

func (x *SubscribeRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SubscribeRequest) GetIntervalMs() uint32 {
	if x != nil {
		return x.IntervalMs
	}
	return 0
}

func (x *SubscribeRequest) GetPayloadSize() uint32 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

// SubscribeResponse is one pushed event.
type SubscribeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Monotonic per-stream sequence number, starting at 1.
	Seq uint64 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	// Event kind label (spike-internal, e.g. "tick").
	Kind string `protobuf:"bytes,2,opt,name=kind,proto3" json:"kind,omitempty"`
	// Daemon wall clock (CLOCK_REALTIME, nanoseconds) at emission time.
	EmittedUnixNanos uint64 `protobuf:"varint,3,opt,name=emitted_unix_nanos,json=emittedUnixNanos,proto3" json:"emitted_unix_nanos,omitempty"`
	// Synthetic payload (payload_size bytes).
	Payload       []byte `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeResponse) Reset() {
	*x = SubscribeResponse{}
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeResponse) ProtoMessage() {}

func (x *SubscribeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeResponse.ProtoReflect.Descriptor instead.
func (*SubscribeResponse) Descriptor() ([]byte, []int) {
	return file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{3}
}

func (x *SubscribeResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SubscribeResponse) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *SubscribeResponse) GetEmittedUnixNanos() uint64 {
	if x != nil {
		return x.EmittedUnixNanos
	}
	return 0
}

func (x *SubscribeResponse) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

// WhoAmIRequest is empty; the caller identity comes from the socket itself.
type WhoAmIRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIRequest) Reset() {
	*x = WhoAmIRequest{}
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIRequest) ProtoMessage() {}

func (x *WhoAmIRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIRequest.ProtoReflect.Descriptor instead.
func (*WhoAmIRequest) Descriptor() ([]byte, []int) {
	return file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{4}
}

// WhoAmIResponse is the server's view of the peer process.
type WhoAmIResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Peer UID from SO_PEERCRED on the accepted Unix socket.
	PeerUid uint32 `protobuf:"varint,1,opt,name=peer_uid,json=peerUid,proto3" json:"peer_uid,omitempty"`
	// Peer PID from SO_PEERCRED (Linux). Informational.
	PeerPid int32 `protobuf:"varint,2,opt,name=peer_pid,json=peerPid,proto3" json:"peer_pid,omitempty"`
	// Peer primary GID from SO_PEERCRED. Informational.
	PeerGid uint32 `protobuf:"varint,3,opt,name=peer_gid,json=peerGid,proto3" json:"peer_gid,omitempty"`
	// Absolute path of the socket the request arrived on.
	SocketPath string `protobuf:"bytes,4,opt,name=socket_path,json=socketPath,proto3" json:"socket_path,omitempty"`
	// Daemon's own effective UID (the expected peer UID).
	ServerUid uint32 `protobuf:"varint,5,opt,name=server_uid,json=serverUid,proto3" json:"server_uid,omitempty"`
	// Whether the daemon enforced a bearer-token check for this call.
	TokenRequired bool `protobuf:"varint,6,opt,name=token_required,json=tokenRequired,proto3" json:"token_required,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WhoAmIResponse) Reset() {
	*x = WhoAmIResponse{}
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WhoAmIResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WhoAmIResponse) ProtoMessage() {}

func (x *WhoAmIResponse) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WhoAmIResponse.ProtoReflect.Descriptor instead.
func (*WhoAmIResponse) Descriptor() ([]byte, []int) {
	return file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescGZIP(), []int{5}
}

func (x *WhoAmIResponse) GetPeerUid() uint32 {
	if x != nil {
		return x.PeerUid
	}
	return 0
}

func (x *WhoAmIResponse) GetPeerPid() int32 {
	if x != nil {
		return x.PeerPid
	}
	return 0
}

func (x *WhoAmIResponse) GetPeerGid() uint32 {
	if x != nil {
		return x.PeerGid
	}
	return 0
}

func (x *WhoAmIResponse) GetSocketPath() string {
	if x != nil {
		return x.SocketPath
	}
	return ""
}

func (x *WhoAmIResponse) GetServerUid() uint32 {
	if x != nil {
		return x.ServerUid
	}
	return 0
}

func (x *WhoAmIResponse) GetTokenRequired() bool {
	if x != nil {
		return x.TokenRequired
	}
	return false
}

var File_phonebridge_spike_localipc_v1_local_ipc_proto protoreflect.FileDescriptor

const file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDesc = "" +
	"\n" +
	"-phonebridge/spike/localipc/v1/local_ipc.proto\x12\x1dphonebridge.spike.localipc.v1\"=\n" +
	"\vPingRequest\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x9a\x01\n" +
	"\fPingResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x123\n" +
	"\x16server_recv_unix_nanos\x18\x04 \x01(\x04R\x13serverRecvUnixNanos\"l\n" +
	"\x10SubscribeRequest\x12\x14\n" +
	"\x05count\x18\x01 \x01(\rR\x05count\x12\x1f\n" +
	"\vinterval_ms\x18\x02 \x01(\rR\n" +
	"intervalMs\x12!\n" +
	"\fpayload_size\x18\x03 \x01(\rR\vpayloadSize\"\x81\x01\n" +
	"\x11SubscribeResponse\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x12\n" +
	"\x04kind\x18\x02 \x01(\tR\x04kind\x12,\n" +
	"\x12emitted_unix_nanos\x18\x03 \x01(\x04R\x10emittedUnixNanos\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\"\x0f\n" +
	"\rWhoAmIRequest\"\xc8\x01\n" +
	"\x0eWhoAmIResponse\x12\x19\n" +
	"\bpeer_uid\x18\x01 \x01(\rR\apeerUid\x12\x19\n" +
	"\bpeer_pid\x18\x02 \x01(\x05R\apeerPid\x12\x19\n" +
	"\bpeer_gid\x18\x03 \x01(\rR\apeerGid\x12\x1f\n" +
	"\vsocket_path\x18\x04 \x01(\tR\n" +
	"socketPath\x12\x1d\n" +
	"\n" +
	"server_uid\x18\x05 \x01(\rR\tserverUid\x12%\n" +
	"\x0etoken_required\x18\x06 \x01(\bR\rtokenRequired2\xd0\x02\n" +
	"\x14LocalIpcSpikeService\x12_\n" +
	"\x04Ping\x12*.phonebridge.spike.localipc.v1.PingRequest\x1a+.phonebridge.spike.localipc.v1.PingResponse\x12p\n" +
	"\tSubscribe\x12/.phonebridge.spike.localipc.v1.SubscribeRequest\x1a0.phonebridge.spike.localipc.v1.SubscribeResponse0\x01\x12e\n" +
	"\x06WhoAmI\x12,.phonebridge.spike.localipc.v1.WhoAmIRequest\x1a-.phonebridge.spike.localipc.v1.WhoAmIResponseBNZLgithub.com/om051p/phonebridge/spikes/localipc-spike/internal/spikepb;spikepbb\x06proto3"

var (
	file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescOnce sync.Once
	file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescData []byte
)

func file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescGZIP() []byte {
	file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescOnce.Do(func() {
		file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDesc), len(file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDesc)))
	})
	return file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDescData
}

var file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_phonebridge_spike_localipc_v1_local_ipc_proto_goTypes = []any{
	(*PingRequest)(nil),       // 0: phonebridge.spike.localipc.v1.PingRequest
	(*PingResponse)(nil),      // 1: phonebridge.spike.localipc.v1.PingResponse
	(*SubscribeRequest)(nil),  // 2: phonebridge.spike.localipc.v1.SubscribeRequest
	(*SubscribeResponse)(nil), // 3: phonebridge.spike.localipc.v1.SubscribeResponse
	(*WhoAmIRequest)(nil),     // 4: phonebridge.spike.localipc.v1.WhoAmIRequest
	(*WhoAmIResponse)(nil),    // 5: phonebridge.spike.localipc.v1.WhoAmIResponse
}
var file_phonebridge_spike_localipc_v1_local_ipc_proto_depIdxs = []int32{
	0, // 0: phonebridge.spike.localipc.v1.LocalIpcSpikeService.Ping:input_type -> phonebridge.spike.localipc.v1.PingRequest
	2, // 1: phonebridge.spike.localipc.v1.LocalIpcSpikeService.Subscribe:input_type -> phonebridge.spike.localipc.v1.SubscribeRequest
	4, // 2: phonebridge.spike.localipc.v1.LocalIpcSpikeService.WhoAmI:input_type -> phonebridge.spike.localipc.v1.WhoAmIRequest
	1, // 3: phonebridge.spike.localipc.v1.LocalIpcSpikeService.Ping:output_type -> phonebridge.spike.localipc.v1.PingResponse
	3, // 4: phonebridge.spike.localipc.v1.LocalIpcSpikeService.Subscribe:output_type -> phonebridge.spike.localipc.v1.SubscribeResponse
	5, // 5: phonebridge.spike.localipc.v1.LocalIpcSpikeService.WhoAmI:output_type -> phonebridge.spike.localipc.v1.WhoAmIResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_phonebridge_spike_localipc_v1_local_ipc_proto_init() }
func file_phonebridge_spike_localipc_v1_local_ipc_proto_init() {
	if File_phonebridge_spike_localipc_v1_local_ipc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDesc), len(file_phonebridge_spike_localipc_v1_local_ipc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_phonebridge_spike_localipc_v1_local_ipc_proto_goTypes,
		DependencyIndexes: file_phonebridge_spike_localipc_v1_local_ipc_proto_depIdxs,
		MessageInfos:      file_phonebridge_spike_localipc_v1_local_ipc_proto_msgTypes,
	}.Build()
	File_phonebridge_spike_localipc_v1_local_ipc_proto = out.File
	file_phonebridge_spike_localipc_v1_local_ipc_proto_goTypes = nil
	file_phonebridge_spike_localipc_v1_local_ipc_proto_depIdxs = nil
}
