// PhoneBridge Spike 01 — provisional local IPC contract (EXPERIMENTAL).
//
// This file exists ONLY to exercise the Flutter <-> Go local transport
// boundary on Linux. It is deliberately NOT `phonebridge.v1`:
//   * `phonebridge.v1` (proto/phonebridge/v1/phonebridge.proto) is the
//     device <-> device wire protocol. It has no `service`, because the
//     local IPC contract is a different boundary with a different trust
//     model (same machine, same user) and is decided by this spike.
//   * Keeping the spike contract separate means the spike cannot freeze or
//     drift the product schema (see docs/decisions.md DEC-014/DEC-015).
//
// The contract is intentionally minimal (Ping/Pong + push + peer identity).
// No product feature is modelled here.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: phonebridge/spike/localipc/v1/local_ipc.proto

package spikepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	LocalIpcSpikeService_Ping_FullMethodName      = "/phonebridge.spike.localipc.v1.LocalIpcSpikeService/Ping"
	LocalIpcSpikeService_Subscribe_FullMethodName = "/phonebridge.spike.localipc.v1.LocalIpcSpikeService/Subscribe"
	LocalIpcSpikeService_WhoAmI_FullMethodName    = "/phonebridge.spike.localipc.v1.LocalIpcSpikeService/WhoAmI"
)

// LocalIpcSpikeServiceClient is the client API for LocalIpcSpikeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// LocalIpcSpikeService is the spike's stand-in for the future local IPC
// service. Only transport-relevant shapes are modelled.
type LocalIpcSpikeServiceClient interface {
	// Ping is the unary round-trip used for feasibility + latency measurement.
	Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error)
	// Subscribe is a server-streaming RPC used to measure Go -> Flutter push
	// (the direction FFI cannot provide without a Dart API DL callback shim).
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error)
	// WhoAmI returns the server's view of the calling process (SO_PEERCRED),
	// which is the basis of the same-user trust boundary.
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error)
}

type localIpcSpikeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewLocalIpcSpikeServiceClient(cc grpc.ClientConnInterface) LocalIpcSpikeServiceClient {
	return &localIpcSpikeServiceClient{cc}
}

func (c *localIpcSpikeServiceClient) Ping(ctx context.Context, in *PingRequest, opts ...grpc.CallOption) (*PingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PingResponse)
	err := c.cc.Invoke(ctx, LocalIpcSpikeService_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *localIpcSpikeServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[SubscribeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &LocalIpcSpikeService_ServiceDesc.Streams[0], LocalIpcSpikeService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, SubscribeResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalIpcSpikeService_SubscribeClient = grpc.ServerStreamingClient[SubscribeResponse]

func (c *localIpcSpikeServiceClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WhoAmIResponse)
	err := c.cc.Invoke(ctx, LocalIpcSpikeService_WhoAmI_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LocalIpcSpikeServiceServer is the server API for LocalIpcSpikeService service.
// All implementations should embed UnimplementedLocalIpcSpikeServiceServer
// for forward compatibility.
//
// LocalIpcSpikeService is the spike's stand-in for the future local IPC
// service. Only transport-relevant shapes are modelled.
type LocalIpcSpikeServiceServer interface {
	// Ping is the unary round-trip used for feasibility + latency measurement.
	Ping(context.Context, *PingRequest) (*PingResponse, error)
	// Subscribe is a server-streaming RPC used to measure Go -> Flutter push
	// (the direction FFI cannot provide without a Dart API DL callback shim).
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error
	// WhoAmI returns the server's view of the calling process (SO_PEERCRED),
	// which is the basis of the same-user trust boundary.
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error)
}

// UnimplementedLocalIpcSpikeServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLocalIpcSpikeServiceServer struct{}

func (UnimplementedLocalIpcSpikeServiceServer) Ping(context.Context, *PingRequest) (*PingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedLocalIpcSpikeServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[SubscribeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedLocalIpcSpikeServiceServer) WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedLocalIpcSpikeServiceServer) testEmbeddedByValue() {}

// UnsafeLocalIpcSpikeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LocalIpcSpikeServiceServer will
// result in compilation errors.
type UnsafeLocalIpcSpikeServiceServer interface {
	mustEmbedUnimplementedLocalIpcSpikeServiceServer()
}

func RegisterLocalIpcSpikeServiceServer(s grpc.ServiceRegistrar, srv LocalIpcSpikeServiceServer) {
	// If the following call pancis, it indicates UnimplementedLocalIpcSpikeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&LocalIpcSpikeService_ServiceDesc, srv)
}

func _LocalIpcSpikeService_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalIpcSpikeServiceServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalIpcSpikeService_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalIpcSpikeServiceServer).Ping(ctx, req.(*PingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _LocalIpcSpikeService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LocalIpcSpikeServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, SubscribeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type LocalIpcSpikeService_SubscribeServer = grpc.ServerStreamingServer[SubscribeResponse]

func _LocalIpcSpikeService_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LocalIpcSpikeServiceServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: LocalIpcSpikeService_WhoAmI_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LocalIpcSpikeServiceServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// LocalIpcSpikeService_ServiceDesc is the grpc.ServiceDesc for LocalIpcSpikeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var LocalIpcSpikeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "phonebridge.spike.localipc.v1.LocalIpcSpikeService",
	HandlerType: (*LocalIpcSpikeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _LocalIpcSpikeService_Ping_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _LocalIpcSpikeService_WhoAmI_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _LocalIpcSpikeService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "phonebridge/spike/localipc/v1/local_ipc.proto",
}
