// PhoneBridge Protocol — v1
// Package: phonebridge.v1
// Status: CONFIRMED (Phase 2, DEC-022) for the device handshake (DeviceHello
// version/capability exchange) and screen-session parameter negotiation
// (ScreenStart/ScreenStop). All other feature payloads remain stubs until
// their own phases.
// Source of truth for wire compatibility: this file + buf breaking checks.
//
// Conventions (see docs/protocol.md):
// - Every application message is framed as Envelope.
// - version/capabilities negotiated via DeviceHello handshake.
// - sequence + nonce provide replay protection per session_id.
// - New fields are optional; removed fields are reserved. New oneof branches
//   are safe for old peers (ignored).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: phonebridge/v1/phonebridge.proto

package phonebridgev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ---------------------------------------------------------------------------
// Capabilities & version negotiation
// ---------------------------------------------------------------------------
type Capability int32

const (
	Capability_CAPABILITY_UNSPECIFIED   Capability = 0
	Capability_CAPABILITY_CLIPBOARD     Capability = 1
	Capability_CAPABILITY_FILES         Capability = 2
	Capability_CAPABILITY_NOTIFICATIONS Capability = 3
	Capability_CAPABILITY_SCREEN        Capability = 4
	Capability_CAPABILITY_INPUT         Capability = 5
	Capability_CAPABILITY_DEVICE_STATUS Capability = 6
)

// Enum value maps for Capability.
var (
	Capability_name = map[int32]string{
		0: "CAPABILITY_UNSPECIFIED",
		1: "CAPABILITY_CLIPBOARD",
		2: "CAPABILITY_FILES",
		3: "CAPABILITY_NOTIFICATIONS",
		4: "CAPABILITY_SCREEN",
		5: "CAPABILITY_INPUT",
		6: "CAPABILITY_DEVICE_STATUS",
	}
	Capability_value = map[string]int32{
		"CAPABILITY_UNSPECIFIED":   0,
		"CAPABILITY_CLIPBOARD":     1,
		"CAPABILITY_FILES":         2,
		"CAPABILITY_NOTIFICATIONS": 3,
		"CAPABILITY_SCREEN":        4,
		"CAPABILITY_INPUT":         5,
		"CAPABILITY_DEVICE_STATUS": 6,
	}
)

func (x Capability) Enum() *Capability {
	p := new(Capability)
	*p = x
	return p
}

func (x Capability) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Capability) Descriptor() protoreflect.EnumDescriptor {
	return file_phonebridge_v1_phonebridge_proto_enumTypes[0].Descriptor()
}

func (Capability) Type() protoreflect.EnumType {
	return &file_phonebridge_v1_phonebridge_proto_enumTypes[0]
}

func (x Capability) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Capability.Descriptor instead.
func (Capability) EnumDescriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{0}
}

// ---------------------------------------------------------------------------
// Error model
// ---------------------------------------------------------------------------
type Code int32

const (
	Code_CODE_UNSPECIFIED          Code = 0
	Code_CODE_OK                   Code = 1
	Code_CODE_INVALID_ARGUMENT     Code = 2
	Code_CODE_UNAUTHENTICATED      Code = 3
	Code_CODE_PERMISSION_DENIED    Code = 4
	Code_CODE_NOT_FOUND            Code = 5
	Code_CODE_ALREADY_EXISTS       Code = 6
	Code_CODE_INCOMPATIBLE_VERSION Code = 7
	Code_CODE_RESOURCE_EXHAUSTED   Code = 8
	Code_CODE_INTERNAL             Code = 9
	Code_CODE_UNAVAILABLE          Code = 10
	// Session negotiation failures (DEC-022). Appended, never renumbered:
	// existing values are wire contracts.
	// The requested MediaParams cannot be satisfied by the capture device.
	Code_CODE_UNSUPPORTED_MEDIA_PARAMS Code = 11
	// The user (or the platform) withdrew MediaProjection consent mid-session.
	// Distinct from a transport failure: the link is healthy and there is
	// simply no longer a screen to send.
	Code_CODE_CONSENT_REVOKED Code = 12
	// Capture or encode failed on the sending device.
	Code_CODE_CAPTURE_FAILED Code = 13
	// The transport (ICE/DTLS/signaling) failed.
	Code_CODE_TRANSPORT_FAILED Code = 14
	// The bounded reconnect window elapsed without the session recovering.
	Code_CODE_RECONNECT_TIMEOUT Code = 15
	// The device already has an active session.
	Code_CODE_SESSION_BUSY Code = 16
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:  "CODE_UNSPECIFIED",
		1:  "CODE_OK",
		2:  "CODE_INVALID_ARGUMENT",
		3:  "CODE_UNAUTHENTICATED",
		4:  "CODE_PERMISSION_DENIED",
		5:  "CODE_NOT_FOUND",
		6:  "CODE_ALREADY_EXISTS",
		7:  "CODE_INCOMPATIBLE_VERSION",
		8:  "CODE_RESOURCE_EXHAUSTED",
		9:  "CODE_INTERNAL",
		10: "CODE_UNAVAILABLE",
		11: "CODE_UNSUPPORTED_MEDIA_PARAMS",
		12: "CODE_CONSENT_REVOKED",
		13: "CODE_CAPTURE_FAILED",
		14: "CODE_TRANSPORT_FAILED",
		15: "CODE_RECONNECT_TIMEOUT",
		16: "CODE_SESSION_BUSY",
	}
	Code_value = map[string]int32{
		"CODE_UNSPECIFIED":              0,
		"CODE_OK":                       1,
		"CODE_INVALID_ARGUMENT":         2,
		"CODE_UNAUTHENTICATED":          3,
		"CODE_PERMISSION_DENIED":        4,
		"CODE_NOT_FOUND":                5,
		"CODE_ALREADY_EXISTS":           6,
		"CODE_INCOMPATIBLE_VERSION":     7,
		"CODE_RESOURCE_EXHAUSTED":       8,
		"CODE_INTERNAL":                 9,
		"CODE_UNAVAILABLE":              10,
		"CODE_UNSUPPORTED_MEDIA_PARAMS": 11,
		"CODE_CONSENT_REVOKED":          12,
		"CODE_CAPTURE_FAILED":           13,
		"CODE_TRANSPORT_FAILED":         14,
		"CODE_RECONNECT_TIMEOUT":        15,
		"CODE_SESSION_BUSY":             16,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_phonebridge_v1_phonebridge_proto_enumTypes[1].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_phonebridge_v1_phonebridge_proto_enumTypes[1]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{1}
}

// ---------------------------------------------------------------------------
// Envelope — top-level framing for every message on the wire.
// ---------------------------------------------------------------------------
type Envelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Protocol version (monotonic uint32). Negotiated via VersionNegotiation.
	Version uint32 `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	// Stable device identity — fingerprint of Ed25519 public key (hex or base64url per spec).
	DeviceId string `protobuf:"bytes,2,opt,name=device_id,json=deviceId,proto3" json:"device_id,omitempty"`
	// Per-connection session identifier (random, e.g. UUID v4).
	SessionId string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// Per-session monotonic sequence. Authoritative ordering; receiver rejects
	// duplicates/old values per replay window.
	Sequence uint64 `protobuf:"varint,4,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// Sender wall-clock in milliseconds since Unix epoch (informational, not ordering).
	TimestampMs uint64 `protobuf:"varint,5,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Per-message nonce for replay-window uniqueness (e.g. 16 random bytes).
	Nonce []byte `protobuf:"bytes,6,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// Sender-advertised capabilities for this session.
	Capabilities *CapabilitySet `protobuf:"bytes,7,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Exactly one payload. Unknown branches must be ignored by older peers.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*Envelope_Ping
	//	*Envelope_Pong
	//	*Envelope_DeviceHello
	//	*Envelope_PairRequest
	//	*Envelope_PairAccept
	//	*Envelope_PairReject
	//	*Envelope_Error
	//	*Envelope_ClipboardUpdate
	//	*Envelope_NotificationEvent
	//	*Envelope_NotificationAction
	//	*Envelope_NotificationDismissed
	//	*Envelope_FileOffer
	//	*Envelope_FileAccept
	//	*Envelope_FileChunk
	//	*Envelope_FileComplete
	//	*Envelope_FileCancel
	//	*Envelope_ScreenStart
	//	*Envelope_ScreenStop
	//	*Envelope_InputKeyboard
	//	*Envelope_InputMouse
	//	*Envelope_InputTouch
	//	*Envelope_DeviceStatus
	Payload       isEnvelope_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Envelope) Reset() {
	*x = Envelope{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Envelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Envelope) ProtoMessage() {}

func (x *Envelope) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Envelope.ProtoReflect.Descriptor instead.
func (*Envelope) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{0}
}

func (x *Envelope) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Envelope) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *Envelope) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Envelope) GetSequence() uint64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Envelope) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *Envelope) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *Envelope) GetCapabilities() *CapabilitySet {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *Envelope) GetPayload() isEnvelope_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Envelope) GetPing() *Ping {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

func (x *Envelope) GetPong() *Pong {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *Envelope) GetDeviceHello() *DeviceHello {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DeviceHello); ok {
			return x.DeviceHello
		}
	}
	return nil
}

func (x *Envelope) GetPairRequest() *PairRequest {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PairRequest); ok {
			return x.PairRequest
		}
	}
	return nil
}

func (x *Envelope) GetPairAccept() *PairAccept {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PairAccept); ok {
			return x.PairAccept
		}
	}
	return nil
}

func (x *Envelope) GetPairReject() *PairReject {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_PairReject); ok {
			return x.PairReject
		}
	}
	return nil
}

func (x *Envelope) GetError() *Error {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Envelope) GetClipboardUpdate() *ClipboardUpdate {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ClipboardUpdate); ok {
			return x.ClipboardUpdate
		}
	}
	return nil
}

func (x *Envelope) GetNotificationEvent() *NotificationEvent {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_NotificationEvent); ok {
			return x.NotificationEvent
		}
	}
	return nil
}

func (x *Envelope) GetNotificationAction() *NotificationAction {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_NotificationAction); ok {
			return x.NotificationAction
		}
	}
	return nil
}

func (x *Envelope) GetNotificationDismissed() *NotificationDismissed {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_NotificationDismissed); ok {
			return x.NotificationDismissed
		}
	}
	return nil
}

func (x *Envelope) GetFileOffer() *FileOffer {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FileOffer); ok {
			return x.FileOffer
		}
	}
	return nil
}

func (x *Envelope) GetFileAccept() *FileAccept {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FileAccept); ok {
			return x.FileAccept
		}
	}
	return nil
}

func (x *Envelope) GetFileChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *Envelope) GetFileComplete() *FileComplete {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FileComplete); ok {
			return x.FileComplete
		}
	}
	return nil
}

func (x *Envelope) GetFileCancel() *FileCancel {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_FileCancel); ok {
			return x.FileCancel
		}
	}
	return nil
}

func (x *Envelope) GetScreenStart() *ScreenStart {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ScreenStart); ok {
			return x.ScreenStart
		}
	}
	return nil
}

func (x *Envelope) GetScreenStop() *ScreenStop {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_ScreenStop); ok {
			return x.ScreenStop
		}
	}
	return nil
}

func (x *Envelope) GetInputKeyboard() *InputKeyboard {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_InputKeyboard); ok {
			return x.InputKeyboard
		}
	}
	return nil
}

func (x *Envelope) GetInputMouse() *InputMouse {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_InputMouse); ok {
			return x.InputMouse
		}
	}
	return nil
}

func (x *Envelope) GetInputTouch() *InputTouch {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_InputTouch); ok {
			return x.InputTouch
		}
	}
	return nil
}

func (x *Envelope) GetDeviceStatus() *DeviceStatus {
	if x != nil {
		if x, ok := x.Payload.(*Envelope_DeviceStatus); ok {
			return x.DeviceStatus
		}
	}
	return nil
}

type isEnvelope_Payload interface {
	isEnvelope_Payload()
}

type Envelope_Ping struct {
	Ping *Ping `protobuf:"bytes,10,opt,name=ping,proto3,oneof"`
}

type Envelope_Pong struct {
	Pong *Pong `protobuf:"bytes,11,opt,name=pong,proto3,oneof"`
}

type Envelope_DeviceHello struct {
	DeviceHello *DeviceHello `protobuf:"bytes,12,opt,name=device_hello,json=deviceHello,proto3,oneof"`
}

type Envelope_PairRequest struct {
	PairRequest *PairRequest `protobuf:"bytes,13,opt,name=pair_request,json=pairRequest,proto3,oneof"`
}

type Envelope_PairAccept struct {
	PairAccept *PairAccept `protobuf:"bytes,14,opt,name=pair_accept,json=pairAccept,proto3,oneof"`
}

type Envelope_PairReject struct {
	PairReject *PairReject `protobuf:"bytes,15,opt,name=pair_reject,json=pairReject,proto3,oneof"`
}

type Envelope_Error struct {
	Error *Error `protobuf:"bytes,16,opt,name=error,proto3,oneof"`
}

type Envelope_ClipboardUpdate struct {
	// Feature payloads — PLANNED stubs (filled in their respective phases).
	ClipboardUpdate *ClipboardUpdate `protobuf:"bytes,20,opt,name=clipboard_update,json=clipboardUpdate,proto3,oneof"` // PLANNED
}

type Envelope_NotificationEvent struct {
	NotificationEvent *NotificationEvent `protobuf:"bytes,21,opt,name=notification_event,json=notificationEvent,proto3,oneof"` // PLANNED
}

type Envelope_NotificationAction struct {
	NotificationAction *NotificationAction `protobuf:"bytes,22,opt,name=notification_action,json=notificationAction,proto3,oneof"` // PLANNED
}

type Envelope_NotificationDismissed struct {
	NotificationDismissed *NotificationDismissed `protobuf:"bytes,23,opt,name=notification_dismissed,json=notificationDismissed,proto3,oneof"` // PLANNED
}

type Envelope_FileOffer struct {
	FileOffer *FileOffer `protobuf:"bytes,24,opt,name=file_offer,json=fileOffer,proto3,oneof"` // PLANNED
}

type Envelope_FileAccept struct {
	FileAccept *FileAccept `protobuf:"bytes,25,opt,name=file_accept,json=fileAccept,proto3,oneof"` // PLANNED
}

type Envelope_FileChunk struct {
	FileChunk *FileChunk `protobuf:"bytes,26,opt,name=file_chunk,json=fileChunk,proto3,oneof"` // PLANNED
}

type Envelope_FileComplete struct {
	FileComplete *FileComplete `protobuf:"bytes,27,opt,name=file_complete,json=fileComplete,proto3,oneof"` // PLANNED
}

type Envelope_FileCancel struct {
	FileCancel *FileCancel `protobuf:"bytes,28,opt,name=file_cancel,json=fileCancel,proto3,oneof"` // PLANNED
}

type Envelope_ScreenStart struct {
	// Screen session negotiation — ratified by DEC-022 (Phase 2).
	ScreenStart *ScreenStart `protobuf:"bytes,29,opt,name=screen_start,json=screenStart,proto3,oneof"`
}

type Envelope_ScreenStop struct {
	ScreenStop *ScreenStop `protobuf:"bytes,30,opt,name=screen_stop,json=screenStop,proto3,oneof"`
}

type Envelope_InputKeyboard struct {
	InputKeyboard *InputKeyboard `protobuf:"bytes,31,opt,name=input_keyboard,json=inputKeyboard,proto3,oneof"` // PLANNED
}

type Envelope_InputMouse struct {
	InputMouse *InputMouse `protobuf:"bytes,32,opt,name=input_mouse,json=inputMouse,proto3,oneof"` // PLANNED
}

type Envelope_InputTouch struct {
	InputTouch *InputTouch `protobuf:"bytes,33,opt,name=input_touch,json=inputTouch,proto3,oneof"` // PLANNED
}

type Envelope_DeviceStatus struct {
	DeviceStatus *DeviceStatus `protobuf:"bytes,34,opt,name=device_status,json=deviceStatus,proto3,oneof"` // PLANNED
}

func (*Envelope_Ping) isEnvelope_Payload() {}

func (*Envelope_Pong) isEnvelope_Payload() {}

func (*Envelope_DeviceHello) isEnvelope_Payload() {}

func (*Envelope_PairRequest) isEnvelope_Payload() {}

func (*Envelope_PairAccept) isEnvelope_Payload() {}

func (*Envelope_PairReject) isEnvelope_Payload() {}

func (*Envelope_Error) isEnvelope_Payload() {}

func (*Envelope_ClipboardUpdate) isEnvelope_Payload() {}

func (*Envelope_NotificationEvent) isEnvelope_Payload() {}

func (*Envelope_NotificationAction) isEnvelope_Payload() {}

func (*Envelope_NotificationDismissed) isEnvelope_Payload() {}

func (*Envelope_FileOffer) isEnvelope_Payload() {}

func (*Envelope_FileAccept) isEnvelope_Payload() {}

func (*Envelope_FileChunk) isEnvelope_Payload() {}

func (*Envelope_FileComplete) isEnvelope_Payload() {}

func (*Envelope_FileCancel) isEnvelope_Payload() {}

func (*Envelope_ScreenStart) isEnvelope_Payload() {}

func (*Envelope_ScreenStop) isEnvelope_Payload() {}

func (*Envelope_InputKeyboard) isEnvelope_Payload() {}

func (*Envelope_InputMouse) isEnvelope_Payload() {}

func (*Envelope_InputTouch) isEnvelope_Payload() {}

func (*Envelope_DeviceStatus) isEnvelope_Payload() {}

type CapabilitySet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Capabilities  []Capability           `protobuf:"varint,1,rep,packed,name=capabilities,proto3,enum=phonebridge.v1.Capability" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapabilitySet) Reset() {
	*x = CapabilitySet{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapabilitySet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapabilitySet) ProtoMessage() {}

func (x *CapabilitySet) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapabilitySet.ProtoReflect.Descriptor instead.
func (*CapabilitySet) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{1}
}

func (x *CapabilitySet) GetCapabilities() []Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type VersionNegotiation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MinVersion    uint32                 `protobuf:"varint,1,opt,name=min_version,json=minVersion,proto3" json:"min_version,omitempty"`
	MaxVersion    uint32                 `protobuf:"varint,2,opt,name=max_version,json=maxVersion,proto3" json:"max_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VersionNegotiation) Reset() {
	*x = VersionNegotiation{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VersionNegotiation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VersionNegotiation) ProtoMessage() {}

func (x *VersionNegotiation) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VersionNegotiation.ProtoReflect.Descriptor instead.
func (*VersionNegotiation) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{2}
}

func (x *VersionNegotiation) GetMinVersion() uint32 {
	if x != nil {
		return x.MinVersion
	}
	return 0
}

func (x *VersionNegotiation) GetMaxVersion() uint32 {
	if x != nil {
		return x.MaxVersion
	}
	return 0
}

// MediaParams is the single definition of a screen-stream parameter tuple.
// It is used in three places so that one shape flows end to end:
//  1. ScreenStart (device protocol) — canonical request/answer form;
//  2. the LAN signaling exchange (DEC-022) — the same fields as JSON;
//  3. the local IPC session snapshot, so the UI renders exactly what was
//     requested and what the capture device actually applied.
//
// An unset field means "no preference / not reported" — proto3 has no explicit
// null, so callers must treat zero values as "unspecified", not as a request
// for a 0-pixel stream.
type MediaParams struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Width  uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`
	Height uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`
	Fps    uint32                 `protobuf:"varint,3,opt,name=fps,proto3" json:"fps,omitempty"`
	// Advisory on Android: DEC-020 records that the platform bitrate control is
	// loose (a 6000 -> 2000 kbps request settled near 1.8x the target). It is
	// carried so both sides can state intent, not as an enforceable limit.
	BitrateKbps uint32 `protobuf:"varint,4,opt,name=bitrate_kbps,json=bitrateKbps,proto3" json:"bitrate_kbps,omitempty"`
	// Codec identifier, e.g. "h264". Empty means "device default".
	Codec         string `protobuf:"bytes,5,opt,name=codec,proto3" json:"codec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaParams) Reset() {
	*x = MediaParams{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaParams) ProtoMessage() {}

func (x *MediaParams) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaParams.ProtoReflect.Descriptor instead.
func (*MediaParams) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{3}
}

func (x *MediaParams) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaParams) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaParams) GetFps() uint32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *MediaParams) GetBitrateKbps() uint32 {
	if x != nil {
		return x.BitrateKbps
	}
	return 0
}

func (x *MediaParams) GetCodec() string {
	if x != nil {
		return x.Codec
	}
	return ""
}

// MediaCapabilities advertises what a device can actually capture for screen
// streaming, so the initiator can request something achievable instead of
// discovering limits through failure. The capture device is authoritative for
// the values it applies (DEC-020).
type MediaCapabilities struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Codec identifiers in preference order (e.g. "h264"). Empty means the
	// device cannot capture a screen stream at all.
	Codecs    []string `protobuf:"bytes,1,rep,name=codecs,proto3" json:"codecs,omitempty"`
	MaxWidth  uint32   `protobuf:"varint,2,opt,name=max_width,json=maxWidth,proto3" json:"max_width,omitempty"`
	MaxHeight uint32   `protobuf:"varint,3,opt,name=max_height,json=maxHeight,proto3" json:"max_height,omitempty"`
	MaxFps    uint32   `protobuf:"varint,4,opt,name=max_fps,json=maxFps,proto3" json:"max_fps,omitempty"`
	// True when the platform can service a screen capture request (Android
	// MediaProjection is consent-gated per session, so this advertises
	// capability, never an existing grant).
	SupportsScreen bool `protobuf:"varint,5,opt,name=supports_screen,json=supportsScreen,proto3" json:"supports_screen,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MediaCapabilities) Reset() {
	*x = MediaCapabilities{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaCapabilities) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaCapabilities) ProtoMessage() {}

func (x *MediaCapabilities) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaCapabilities.ProtoReflect.Descriptor instead.
func (*MediaCapabilities) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{4}
}

func (x *MediaCapabilities) GetCodecs() []string {
	if x != nil {
		return x.Codecs
	}
	return nil
}

func (x *MediaCapabilities) GetMaxWidth() uint32 {
	if x != nil {
		return x.MaxWidth
	}
	return 0
}

func (x *MediaCapabilities) GetMaxHeight() uint32 {
	if x != nil {
		return x.MaxHeight
	}
	return 0
}

func (x *MediaCapabilities) GetMaxFps() uint32 {
	if x != nil {
		return x.MaxFps
	}
	return 0
}

func (x *MediaCapabilities) GetSupportsScreen() bool {
	if x != nil {
		return x.SupportsScreen
	}
	return false
}

// ---------------------------------------------------------------------------
// Control / handshake.
// DeviceHello's version/capability/media advertising is CONFIRMED (Phase 2,
// DEC-022) and exchanged before any media. The PairRequest/PairAccept payloads
// remain EXPERIMENTAL: the validated pairing flow runs through the
// authenticated LAN exchange (DEC-022) and does not yet carry these payloads.
// ---------------------------------------------------------------------------
type DeviceHello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Human-readable device name.
	DisplayName string `protobuf:"bytes,1,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	// Platform identifier (e.g. "android", "linux").
	Platform string `protobuf:"bytes,2,opt,name=platform,proto3" json:"platform,omitempty"`
	// Ed25519 public key (raw 32 bytes) or fingerprint — exact encoding TBD (EXPERIMENTAL).
	IdentityPubkey     []byte              `protobuf:"bytes,3,opt,name=identity_pubkey,json=identityPubkey,proto3" json:"identity_pubkey,omitempty"`
	VersionNegotiation *VersionNegotiation `protobuf:"bytes,4,opt,name=version_negotiation,json=versionNegotiation,proto3" json:"version_negotiation,omitempty"`
	Capabilities       *CapabilitySet      `protobuf:"bytes,5,opt,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Screen-streaming limits, present when CAPABILITY_SCREEN is advertised.
	Media         *MediaCapabilities `protobuf:"bytes,6,opt,name=media,proto3" json:"media,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceHello) Reset() {
	*x = DeviceHello{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceHello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceHello) ProtoMessage() {}

func (x *DeviceHello) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceHello.ProtoReflect.Descriptor instead.
func (*DeviceHello) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{5}
}

func (x *DeviceHello) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *DeviceHello) GetPlatform() string {
	if x != nil {
		return x.Platform
	}
	return ""
}

func (x *DeviceHello) GetIdentityPubkey() []byte {
	if x != nil {
		return x.IdentityPubkey
	}
	return nil
}

func (x *DeviceHello) GetVersionNegotiation() *VersionNegotiation {
	if x != nil {
		return x.VersionNegotiation
	}
	return nil
}

func (x *DeviceHello) GetCapabilities() *CapabilitySet {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *DeviceHello) GetMedia() *MediaCapabilities {
	if x != nil {
		return x.Media
	}
	return nil
}

type PairRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hello *DeviceHello           `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	// QR / rendezvous correlation id.
	PairingToken  string `protobuf:"bytes,2,opt,name=pairing_token,json=pairingToken,proto3" json:"pairing_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairRequest) Reset() {
	*x = PairRequest{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairRequest) ProtoMessage() {}

func (x *PairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairRequest.ProtoReflect.Descriptor instead.
func (*PairRequest) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{6}
}

func (x *PairRequest) GetHello() *DeviceHello {
	if x != nil {
		return x.Hello
	}
	return nil
}

func (x *PairRequest) GetPairingToken() string {
	if x != nil {
		return x.PairingToken
	}
	return ""
}

type PairAccept struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Hello *DeviceHello           `protobuf:"bytes,1,opt,name=hello,proto3" json:"hello,omitempty"`
	// Short Authentication String (human-verified).
	Sas           string `protobuf:"bytes,2,opt,name=sas,proto3" json:"sas,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairAccept) Reset() {
	*x = PairAccept{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairAccept) ProtoMessage() {}

func (x *PairAccept) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairAccept.ProtoReflect.Descriptor instead.
func (*PairAccept) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{7}
}

func (x *PairAccept) GetHello() *DeviceHello {
	if x != nil {
		return x.Hello
	}
	return nil
}

func (x *PairAccept) GetSas() string {
	if x != nil {
		return x.Sas
	}
	return ""
}

type PairReject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         *Error                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PairReject) Reset() {
	*x = PairReject{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PairReject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairReject) ProtoMessage() {}

func (x *PairReject) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairReject.ProtoReflect.Descriptor instead.
func (*PairReject) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{8}
}

func (x *PairReject) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{9}
}

func (x *Ping) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Pong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         uint64                 `protobuf:"varint,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{10}
}

func (x *Pong) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=phonebridge.v1.Code" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       map[string]string      `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{11}
}

func (x *Error) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_CODE_UNSPECIFIED
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetails() map[string]string {
	if x != nil {
		return x.Details
	}
	return nil
}

// ---------------------------------------------------------------------------
// Screen session negotiation (DEC-022, Phase 2)
// ---------------------------------------------------------------------------
// ScreenStart carries the capture request and the capture device's answer.
// The parameter tuple is MediaParams (below), so the request, the LAN
// signaling exchange (DEC-022) and the local IPC session snapshot all speak
// one shape.
//
// Contract, in order:
//  1. The initiator sends ScreenStart with `requested` populated and no
//     answer fields. Android requires a MediaProjection consent before any
//     capture exists (DEC-020), so parameters must be settled BEFORE the
//     offer is composed and never mid-stream.
//  2. The capture device replies with `accepted` + `actual` — always. A
//     reply that differs from `requested` is a reported downgrade, never a
//     silent substitution: the initiator can compare the two tuples and
//     tell the user what is really being sent.
//  3. If nothing within the device's MediaCapabilities can satisfy the
//     request, `accepted` is false and `reject_reason` says why.
//
// Resolution changes are never negotiated in-session: DEC-020 records that a
// new geometry needs a new consent and a new session.
type ScreenStart struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// What the initiator asked for. Zero fields mean "no preference".
	Requested *MediaParams `protobuf:"bytes,1,opt,name=requested,proto3" json:"requested,omitempty"`
	// True when `actual` equals `requested` exactly.
	Accepted bool `protobuf:"varint,2,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// Set when `accepted` is false: why the request could not be met.
	RejectReason string `protobuf:"bytes,3,opt,name=reject_reason,json=rejectReason,proto3" json:"reject_reason,omitempty"`
	// What the capture device actually applied. Authoritative (DEC-020); the
	// initiator must treat this as the truth for display and diagnostics.
	Actual        *MediaParams `protobuf:"bytes,4,opt,name=actual,proto3" json:"actual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenStart) Reset() {
	*x = ScreenStart{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenStart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenStart) ProtoMessage() {}

func (x *ScreenStart) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenStart.ProtoReflect.Descriptor instead.
func (*ScreenStart) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{12}
}

func (x *ScreenStart) GetRequested() *MediaParams {
	if x != nil {
		return x.Requested
	}
	return nil
}

func (x *ScreenStart) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *ScreenStart) GetRejectReason() string {
	if x != nil {
		return x.RejectReason
	}
	return ""
}

func (x *ScreenStart) GetActual() *MediaParams {
	if x != nil {
		return x.Actual
	}
	return nil
}

// ---------------------------------------------------------------------------
// Feature payloads — PLANNED stubs. No fields populated in Phase 0.
// Each will be expanded in its feature phase with reserved ranges preserved.
// ---------------------------------------------------------------------------
type ClipboardUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClipboardUpdate) Reset() {
	*x = ClipboardUpdate{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClipboardUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClipboardUpdate) ProtoMessage() {}

func (x *ClipboardUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClipboardUpdate.ProtoReflect.Descriptor instead.
func (*ClipboardUpdate) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{13}
}

type NotificationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationEvent) Reset() {
	*x = NotificationEvent{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationEvent) ProtoMessage() {}

func (x *NotificationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationEvent.ProtoReflect.Descriptor instead.
func (*NotificationEvent) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{14}
}

type NotificationAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationAction) Reset() {
	*x = NotificationAction{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationAction) ProtoMessage() {}

func (x *NotificationAction) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationAction.ProtoReflect.Descriptor instead.
func (*NotificationAction) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{15}
}

type NotificationDismissed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationDismissed) Reset() {
	*x = NotificationDismissed{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationDismissed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationDismissed) ProtoMessage() {}

func (x *NotificationDismissed) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationDismissed.ProtoReflect.Descriptor instead.
func (*NotificationDismissed) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{16}
}

type FileOffer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileOffer) Reset() {
	*x = FileOffer{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileOffer) ProtoMessage() {}

func (x *FileOffer) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileOffer.ProtoReflect.Descriptor instead.
func (*FileOffer) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{17}
}

type FileAccept struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileAccept) Reset() {
	*x = FileAccept{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileAccept) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileAccept) ProtoMessage() {}

func (x *FileAccept) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileAccept.ProtoReflect.Descriptor instead.
func (*FileAccept) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{18}
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{19}
}

type FileComplete struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileComplete) Reset() {
	*x = FileComplete{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileComplete) ProtoMessage() {}

func (x *FileComplete) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileComplete.ProtoReflect.Descriptor instead.
func (*FileComplete) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{20}
}

type FileCancel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileCancel) Reset() {
	*x = FileCancel{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileCancel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileCancel) ProtoMessage() {}

func (x *FileCancel) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileCancel.ProtoReflect.Descriptor instead.
func (*FileCancel) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{21}
}

type ScreenStop struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Why the stream stopped (typed where the sender knows the cause).
	ReasonCode Code `protobuf:"varint,1,opt,name=reason_code,json=reasonCode,proto3,enum=phonebridge.v1.Code" json:"reason_code,omitempty"`
	// Human-readable detail for logs and diagnostics; never parsed by code.
	Reason        string `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScreenStop) Reset() {
	*x = ScreenStop{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScreenStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScreenStop) ProtoMessage() {}

func (x *ScreenStop) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScreenStop.ProtoReflect.Descriptor instead.
func (*ScreenStop) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{22}
}

func (x *ScreenStop) GetReasonCode() Code {
	if x != nil {
		return x.ReasonCode
	}
	return Code_CODE_UNSPECIFIED
}

func (x *ScreenStop) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type InputKeyboard struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputKeyboard) Reset() {
	*x = InputKeyboard{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputKeyboard) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputKeyboard) ProtoMessage() {}

func (x *InputKeyboard) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputKeyboard.ProtoReflect.Descriptor instead.
func (*InputKeyboard) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{23}
}

type InputMouse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputMouse) Reset() {
	*x = InputMouse{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputMouse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputMouse) ProtoMessage() {}

func (x *InputMouse) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputMouse.ProtoReflect.Descriptor instead.
func (*InputMouse) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{24}
}

type InputTouch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InputTouch) Reset() {
	*x = InputTouch{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InputTouch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InputTouch) ProtoMessage() {}

func (x *InputTouch) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InputTouch.ProtoReflect.Descriptor instead.
func (*InputTouch) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{25}
}

type DeviceStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeviceStatus) Reset() {
	*x = DeviceStatus{}
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeviceStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeviceStatus) ProtoMessage() {}

func (x *DeviceStatus) ProtoReflect() protoreflect.Message {
	mi := &file_phonebridge_v1_phonebridge_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeviceStatus.ProtoReflect.Descriptor instead.
func (*DeviceStatus) Descriptor() ([]byte, []int) {
	return file_phonebridge_v1_phonebridge_proto_rawDescGZIP(), []int{26}
}

var File_phonebridge_v1_phonebridge_proto protoreflect.FileDescriptor

const file_phonebridge_v1_phonebridge_proto_rawDesc = "" +
	"\n" +
	" phonebridge/v1/phonebridge.proto\x12\x0ephonebridge.v1\"\xb8\r\n" +
	"\bEnvelope\x12\x18\n" +
	"\aversion\x18\x01 \x01(\rR\aversion\x12\x1b\n" +
	"\tdevice_id\x18\x02 \x01(\tR\bdeviceId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\x12\x1a\n" +
	"\bsequence\x18\x04 \x01(\x04R\bsequence\x12!\n" +
	"\ftimestamp_ms\x18\x05 \x01(\x04R\vtimestampMs\x12\x14\n" +
	"\x05nonce\x18\x06 \x01(\fR\x05nonce\x12A\n" +
	"\fcapabilities\x18\a \x01(\v2\x1d.phonebridge.v1.CapabilitySetR\fcapabilities\x12*\n" +
	"\x04ping\x18\n" +
	" \x01(\v2\x14.phonebridge.v1.PingH\x00R\x04ping\x12*\n" +
	"\x04pong\x18\v \x01(\v2\x14.phonebridge.v1.PongH\x00R\x04pong\x12@\n" +
	"\fdevice_hello\x18\f \x01(\v2\x1b.phonebridge.v1.DeviceHelloH\x00R\vdeviceHello\x12@\n" +
	"\fpair_request\x18\r \x01(\v2\x1b.phonebridge.v1.PairRequestH\x00R\vpairRequest\x12=\n" +
	"\vpair_accept\x18\x0e \x01(\v2\x1a.phonebridge.v1.PairAcceptH\x00R\n" +
	"pairAccept\x12=\n" +
	"\vpair_reject\x18\x0f \x01(\v2\x1a.phonebridge.v1.PairRejectH\x00R\n" +
	"pairReject\x12-\n" +
	"\x05error\x18\x10 \x01(\v2\x15.phonebridge.v1.ErrorH\x00R\x05error\x12L\n" +
	"\x10clipboard_update\x18\x14 \x01(\v2\x1f.phonebridge.v1.ClipboardUpdateH\x00R\x0fclipboardUpdate\x12R\n" +
	"\x12notification_event\x18\x15 \x01(\v2!.phonebridge.v1.NotificationEventH\x00R\x11notificationEvent\x12U\n" +
	"\x13notification_action\x18\x16 \x01(\v2\".phonebridge.v1.NotificationActionH\x00R\x12notificationAction\x12^\n" +
	"\x16notification_dismissed\x18\x17 \x01(\v2%.phonebridge.v1.NotificationDismissedH\x00R\x15notificationDismissed\x12:\n" +
	"\n" +
	"file_offer\x18\x18 \x01(\v2\x19.phonebridge.v1.FileOfferH\x00R\tfileOffer\x12=\n" +
	"\vfile_accept\x18\x19 \x01(\v2\x1a.phonebridge.v1.FileAcceptH\x00R\n" +
	"fileAccept\x12:\n" +
	"\n" +
	"file_chunk\x18\x1a \x01(\v2\x19.phonebridge.v1.FileChunkH\x00R\tfileChunk\x12C\n" +
	"\rfile_complete\x18\x1b \x01(\v2\x1c.phonebridge.v1.FileCompleteH\x00R\ffileComplete\x12=\n" +
	"\vfile_cancel\x18\x1c \x01(\v2\x1a.phonebridge.v1.FileCancelH\x00R\n" +
	"fileCancel\x12@\n" +
	"\fscreen_start\x18\x1d \x01(\v2\x1b.phonebridge.v1.ScreenStartH\x00R\vscreenStart\x12=\n" +
	"\vscreen_stop\x18\x1e \x01(\v2\x1a.phonebridge.v1.ScreenStopH\x00R\n" +
	"screenStop\x12F\n" +
	"\x0einput_keyboard\x18\x1f \x01(\v2\x1d.phonebridge.v1.InputKeyboardH\x00R\rinputKeyboard\x12=\n" +
	"\vinput_mouse\x18  \x01(\v2\x1a.phonebridge.v1.InputMouseH\x00R\n" +
	"inputMouse\x12=\n" +
	"\vinput_touch\x18! \x01(\v2\x1a.phonebridge.v1.InputTouchH\x00R\n" +
	"inputTouch\x12C\n" +
	"\rdevice_status\x18\" \x01(\v2\x1c.phonebridge.v1.DeviceStatusH\x00R\fdeviceStatusB\t\n" +
	"\apayloadJ\x04\b\b\x10\tJ\x04\b\t\x10\n" +
	"\"O\n" +
	"\rCapabilitySet\x12>\n" +
	"\fcapabilities\x18\x01 \x03(\x0e2\x1a.phonebridge.v1.CapabilityR\fcapabilities\"V\n" +
	"\x12VersionNegotiation\x12\x1f\n" +
	"\vmin_version\x18\x01 \x01(\rR\n" +
	"minVersion\x12\x1f\n" +
	"\vmax_version\x18\x02 \x01(\rR\n" +
	"maxVersion\"\x86\x01\n" +
	"\vMediaParams\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x10\n" +
	"\x03fps\x18\x03 \x01(\rR\x03fps\x12!\n" +
	"\fbitrate_kbps\x18\x04 \x01(\rR\vbitrateKbps\x12\x14\n" +
	"\x05codec\x18\x05 \x01(\tR\x05codec\"\xa9\x01\n" +
	"\x11MediaCapabilities\x12\x16\n" +
	"\x06codecs\x18\x01 \x03(\tR\x06codecs\x12\x1b\n" +
	"\tmax_width\x18\x02 \x01(\rR\bmaxWidth\x12\x1d\n" +
	"\n" +
	"max_height\x18\x03 \x01(\rR\tmaxHeight\x12\x17\n" +
	"\amax_fps\x18\x04 \x01(\rR\x06maxFps\x12'\n" +
	"\x0fsupports_screen\x18\x05 \x01(\bR\x0esupportsScreen\"\xc6\x02\n" +
	"\vDeviceHello\x12!\n" +
	"\fdisplay_name\x18\x01 \x01(\tR\vdisplayName\x12\x1a\n" +
	"\bplatform\x18\x02 \x01(\tR\bplatform\x12'\n" +
	"\x0fidentity_pubkey\x18\x03 \x01(\fR\x0eidentityPubkey\x12S\n" +
	"\x13version_negotiation\x18\x04 \x01(\v2\".phonebridge.v1.VersionNegotiationR\x12versionNegotiation\x12A\n" +
	"\fcapabilities\x18\x05 \x01(\v2\x1d.phonebridge.v1.CapabilitySetR\fcapabilities\x127\n" +
	"\x05media\x18\x06 \x01(\v2!.phonebridge.v1.MediaCapabilitiesR\x05media\"e\n" +
	"\vPairRequest\x121\n" +
	"\x05hello\x18\x01 \x01(\v2\x1b.phonebridge.v1.DeviceHelloR\x05hello\x12#\n" +
	"\rpairing_token\x18\x02 \x01(\tR\fpairingToken\"Q\n" +
	"\n" +
	"PairAccept\x121\n" +
	"\x05hello\x18\x01 \x01(\v2\x1b.phonebridge.v1.DeviceHelloR\x05hello\x12\x10\n" +
	"\x03sas\x18\x02 \x01(\tR\x03sas\"9\n" +
	"\n" +
	"PairReject\x12+\n" +
	"\x05error\x18\x01 \x01(\v2\x15.phonebridge.v1.ErrorR\x05error\"\x1c\n" +
	"\x04Ping\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\x1c\n" +
	"\x04Pong\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\x04R\x05nonce\"\xc5\x01\n" +
	"\x05Error\x12(\n" +
	"\x04code\x18\x01 \x01(\x0e2\x14.phonebridge.v1.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12<\n" +
	"\adetails\x18\x03 \x03(\v2\".phonebridge.v1.Error.DetailsEntryR\adetails\x1a:\n" +
	"\fDetailsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xbe\x01\n" +
	"\vScreenStart\x129\n" +
	"\trequested\x18\x01 \x01(\v2\x1b.phonebridge.v1.MediaParamsR\trequested\x12\x1a\n" +
	"\baccepted\x18\x02 \x01(\bR\baccepted\x12#\n" +
	"\rreject_reason\x18\x03 \x01(\tR\frejectReason\x123\n" +
	"\x06actual\x18\x04 \x01(\v2\x1b.phonebridge.v1.MediaParamsR\x06actual\"\x11\n" +
	"\x0fClipboardUpdate\"\x13\n" +
	"\x11NotificationEvent\"\x14\n" +
	"\x12NotificationAction\"\x17\n" +
	"\x15NotificationDismissed\"\v\n" +
	"\tFileOffer\"\f\n" +
	"\n" +
	"FileAccept\"\v\n" +
	"\tFileChunk\"\x0e\n" +
	"\fFileComplete\"\f\n" +
	"\n" +
	"FileCancel\"[\n" +
	"\n" +
	"ScreenStop\x125\n" +
	"\vreason_code\x18\x01 \x01(\x0e2\x14.phonebridge.v1.CodeR\n" +
	"reasonCode\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x0f\n" +
	"\rInputKeyboard\"\f\n" +
	"\n" +
	"InputMouse\"\f\n" +
	"\n" +
	"InputTouch\"\x0e\n" +
	"\fDeviceStatus*\xc1\x01\n" +
	"\n" +
	"Capability\x12\x1a\n" +
	"\x16CAPABILITY_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14CAPABILITY_CLIPBOARD\x10\x01\x12\x14\n" +
	"\x10CAPABILITY_FILES\x10\x02\x12\x1c\n" +
	"\x18CAPABILITY_NOTIFICATIONS\x10\x03\x12\x15\n" +
	"\x11CAPABILITY_SCREEN\x10\x04\x12\x14\n" +
	"\x10CAPABILITY_INPUT\x10\x05\x12\x1c\n" +
	"\x18CAPABILITY_DEVICE_STATUS\x10\x06*\xb0\x03\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCODE_OK\x10\x01\x12\x19\n" +
	"\x15CODE_INVALID_ARGUMENT\x10\x02\x12\x18\n" +
	"\x14CODE_UNAUTHENTICATED\x10\x03\x12\x1a\n" +
	"\x16CODE_PERMISSION_DENIED\x10\x04\x12\x12\n" +
	"\x0eCODE_NOT_FOUND\x10\x05\x12\x17\n" +
	"\x13CODE_ALREADY_EXISTS\x10\x06\x12\x1d\n" +
	"\x19CODE_INCOMPATIBLE_VERSION\x10\a\x12\x1b\n" +
	"\x17CODE_RESOURCE_EXHAUSTED\x10\b\x12\x11\n" +
	"\rCODE_INTERNAL\x10\t\x12\x14\n" +
	"\x10CODE_UNAVAILABLE\x10\n" +
	"\x12!\n" +
	"\x1dCODE_UNSUPPORTED_MEDIA_PARAMS\x10\v\x12\x18\n" +
	"\x14CODE_CONSENT_REVOKED\x10\f\x12\x17\n" +
	"\x13CODE_CAPTURE_FAILED\x10\r\x12\x19\n" +
	"\x15CODE_TRANSPORT_FAILED\x10\x0e\x12\x1a\n" +
	"\x16CODE_RECONNECT_TIMEOUT\x10\x0f\x12\x15\n" +
	"\x11CODE_SESSION_BUSY\x10\x10Bi\n" +
	"\x18dev.phonebridge.proto.v1P\x01ZKgithub.com/om051p/phonebridge/core/pkg/protocol/phonebridgev1;phonebridgev1b\x06proto3"

var (
	file_phonebridge_v1_phonebridge_proto_rawDescOnce sync.Once
	file_phonebridge_v1_phonebridge_proto_rawDescData []byte
)

func file_phonebridge_v1_phonebridge_proto_rawDescGZIP() []byte {
	file_phonebridge_v1_phonebridge_proto_rawDescOnce.Do(func() {
		file_phonebridge_v1_phonebridge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_phonebridge_v1_phonebridge_proto_rawDesc), len(file_phonebridge_v1_phonebridge_proto_rawDesc)))
	})
	return file_phonebridge_v1_phonebridge_proto_rawDescData
}

var file_phonebridge_v1_phonebridge_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_phonebridge_v1_phonebridge_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_phonebridge_v1_phonebridge_proto_goTypes = []any{
	(Capability)(0),               // 0: phonebridge.v1.Capability
	(Code)(0),                     // 1: phonebridge.v1.Code
	(*Envelope)(nil),              // 2: phonebridge.v1.Envelope
	(*CapabilitySet)(nil),         // 3: phonebridge.v1.CapabilitySet
	(*VersionNegotiation)(nil),    // 4: phonebridge.v1.VersionNegotiation
	(*MediaParams)(nil),           // 5: phonebridge.v1.MediaParams
	(*MediaCapabilities)(nil),     // 6: phonebridge.v1.MediaCapabilities
	(*DeviceHello)(nil),           // 7: phonebridge.v1.DeviceHello
	(*PairRequest)(nil),           // 8: phonebridge.v1.PairRequest
	(*PairAccept)(nil),            // 9: phonebridge.v1.PairAccept
	(*PairReject)(nil),            // 10: phonebridge.v1.PairReject
	(*Ping)(nil),                  // 11: phonebridge.v1.Ping
	(*Pong)(nil),                  // 12: phonebridge.v1.Pong
	(*Error)(nil),                 // 13: phonebridge.v1.Error
	(*ScreenStart)(nil),           // 14: phonebridge.v1.ScreenStart
	(*ClipboardUpdate)(nil),       // 15: phonebridge.v1.ClipboardUpdate
	(*NotificationEvent)(nil),     // 16: phonebridge.v1.NotificationEvent
	(*NotificationAction)(nil),    // 17: phonebridge.v1.NotificationAction
	(*NotificationDismissed)(nil), // 18: phonebridge.v1.NotificationDismissed
	(*FileOffer)(nil),             // 19: phonebridge.v1.FileOffer
	(*FileAccept)(nil),            // 20: phonebridge.v1.FileAccept
	(*FileChunk)(nil),             // 21: phonebridge.v1.FileChunk
	(*FileComplete)(nil),          // 22: phonebridge.v1.FileComplete
	(*FileCancel)(nil),            // 23: phonebridge.v1.FileCancel
	(*ScreenStop)(nil),            // 24: phonebridge.v1.ScreenStop
	(*InputKeyboard)(nil),         // 25: phonebridge.v1.InputKeyboard
	(*InputMouse)(nil),            // 26: phonebridge.v1.InputMouse
	(*InputTouch)(nil),            // 27: phonebridge.v1.InputTouch
	(*DeviceStatus)(nil),          // 28: phonebridge.v1.DeviceStatus
	nil,                           // 29: phonebridge.v1.Error.DetailsEntry
}
var file_phonebridge_v1_phonebridge_proto_depIdxs = []int32{
	3,  // 0: phonebridge.v1.Envelope.capabilities:type_name -> phonebridge.v1.CapabilitySet
	11, // 1: phonebridge.v1.Envelope.ping:type_name -> phonebridge.v1.Ping
	12, // 2: phonebridge.v1.Envelope.pong:type_name -> phonebridge.v1.Pong
	7,  // 3: phonebridge.v1.Envelope.device_hello:type_name -> phonebridge.v1.DeviceHello
	8,  // 4: phonebridge.v1.Envelope.pair_request:type_name -> phonebridge.v1.PairRequest
	9,  // 5: phonebridge.v1.Envelope.pair_accept:type_name -> phonebridge.v1.PairAccept
	10, // 6: phonebridge.v1.Envelope.pair_reject:type_name -> phonebridge.v1.PairReject
	13, // 7: phonebridge.v1.Envelope.error:type_name -> phonebridge.v1.Error
	15, // 8: phonebridge.v1.Envelope.clipboard_update:type_name -> phonebridge.v1.ClipboardUpdate
	16, // 9: phonebridge.v1.Envelope.notification_event:type_name -> phonebridge.v1.NotificationEvent
	17, // 10: phonebridge.v1.Envelope.notification_action:type_name -> phonebridge.v1.NotificationAction
	18, // 11: phonebridge.v1.Envelope.notification_dismissed:type_name -> phonebridge.v1.NotificationDismissed
	19, // 12: phonebridge.v1.Envelope.file_offer:type_name -> phonebridge.v1.FileOffer
	20, // 13: phonebridge.v1.Envelope.file_accept:type_name -> phonebridge.v1.FileAccept
	21, // 14: phonebridge.v1.Envelope.file_chunk:type_name -> phonebridge.v1.FileChunk
	22, // 15: phonebridge.v1.Envelope.file_complete:type_name -> phonebridge.v1.FileComplete
	23, // 16: phonebridge.v1.Envelope.file_cancel:type_name -> phonebridge.v1.FileCancel
	14, // 17: phonebridge.v1.Envelope.screen_start:type_name -> phonebridge.v1.ScreenStart
	24, // 18: phonebridge.v1.Envelope.screen_stop:type_name -> phonebridge.v1.ScreenStop
	25, // 19: phonebridge.v1.Envelope.input_keyboard:type_name -> phonebridge.v1.InputKeyboard
	26, // 20: phonebridge.v1.Envelope.input_mouse:type_name -> phonebridge.v1.InputMouse
	27, // 21: phonebridge.v1.Envelope.input_touch:type_name -> phonebridge.v1.InputTouch
	28, // 22: phonebridge.v1.Envelope.device_status:type_name -> phonebridge.v1.DeviceStatus
	0,  // 23: phonebridge.v1.CapabilitySet.capabilities:type_name -> phonebridge.v1.Capability
	4,  // 24: phonebridge.v1.DeviceHello.version_negotiation:type_name -> phonebridge.v1.VersionNegotiation
	3,  // 25: phonebridge.v1.DeviceHello.capabilities:type_name -> phonebridge.v1.CapabilitySet
	6,  // 26: phonebridge.v1.DeviceHello.media:type_name -> phonebridge.v1.MediaCapabilities
	7,  // 27: phonebridge.v1.PairRequest.hello:type_name -> phonebridge.v1.DeviceHello
	7,  // 28: phonebridge.v1.PairAccept.hello:type_name -> phonebridge.v1.DeviceHello
	13, // 29: phonebridge.v1.PairReject.error:type_name -> phonebridge.v1.Error
	1,  // 30: phonebridge.v1.Error.code:type_name -> phonebridge.v1.Code
	29, // 31: phonebridge.v1.Error.details:type_name -> phonebridge.v1.Error.DetailsEntry
	5,  // 32: phonebridge.v1.ScreenStart.requested:type_name -> phonebridge.v1.MediaParams
	5,  // 33: phonebridge.v1.ScreenStart.actual:type_name -> phonebridge.v1.MediaParams
	1,  // 34: phonebridge.v1.ScreenStop.reason_code:type_name -> phonebridge.v1.Code
	35, // [35:35] is the sub-list for method output_type
	35, // [35:35] is the sub-list for method input_type
	35, // [35:35] is the sub-list for extension type_name
	35, // [35:35] is the sub-list for extension extendee
	0,  // [0:35] is the sub-list for field type_name
}

func init() { file_phonebridge_v1_phonebridge_proto_init() }
func file_phonebridge_v1_phonebridge_proto_init() {
	if File_phonebridge_v1_phonebridge_proto != nil {
		return
	}
	file_phonebridge_v1_phonebridge_proto_msgTypes[0].OneofWrappers = []any{
		(*Envelope_Ping)(nil),
		(*Envelope_Pong)(nil),
		(*Envelope_DeviceHello)(nil),
		(*Envelope_PairRequest)(nil),
		(*Envelope_PairAccept)(nil),
		(*Envelope_PairReject)(nil),
		(*Envelope_Error)(nil),
		(*Envelope_ClipboardUpdate)(nil),
		(*Envelope_NotificationEvent)(nil),
		(*Envelope_NotificationAction)(nil),
		(*Envelope_NotificationDismissed)(nil),
		(*Envelope_FileOffer)(nil),
		(*Envelope_FileAccept)(nil),
		(*Envelope_FileChunk)(nil),
		(*Envelope_FileComplete)(nil),
		(*Envelope_FileCancel)(nil),
		(*Envelope_ScreenStart)(nil),
		(*Envelope_ScreenStop)(nil),
		(*Envelope_InputKeyboard)(nil),
		(*Envelope_InputMouse)(nil),
		(*Envelope_InputTouch)(nil),
		(*Envelope_DeviceStatus)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_phonebridge_v1_phonebridge_proto_rawDesc), len(file_phonebridge_v1_phonebridge_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_phonebridge_v1_phonebridge_proto_goTypes,
		DependencyIndexes: file_phonebridge_v1_phonebridge_proto_depIdxs,
		EnumInfos:         file_phonebridge_v1_phonebridge_proto_enumTypes,
		MessageInfos:      file_phonebridge_v1_phonebridge_proto_msgTypes,
	}.Build()
	File_phonebridge_v1_phonebridge_proto = out.File
	file_phonebridge_v1_phonebridge_proto_goTypes = nil
	file_phonebridge_v1_phonebridge_proto_depIdxs = nil
}
